/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type {
  AdminSystemPositionDelete200,
  AdminSystemPositionDeleteMutationResponse,
  AdminSystemPositionDeletePathParams,
} from '../../models/AdminSystemPositionDelete';

import { createCommonResFaker } from '../createCommonResFaker';
import { createEmptyResFaker } from '../createEmptyResFaker';

export function createAdminSystemPositionDeletePathParamsFaker(data?: Partial<AdminSystemPositionDeletePathParams>): AdminSystemPositionDeletePathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description 非查询返回
 */
export function createAdminSystemPositionDelete200Faker(data?: Partial<AdminSystemPositionDelete200>): AdminSystemPositionDelete200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: faker.string.alpha() });
}

export function createAdminSystemPositionDeleteMutationRequestFaker() {
  faker.seed([2021]);
  return createEmptyResFaker();
}

export function createAdminSystemPositionDeleteMutationResponseFaker(
  data?: Partial<AdminSystemPositionDeleteMutationResponse>,
): AdminSystemPositionDeleteMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemPositionDelete200Faker()]);
}
