/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemPositionGet200, AdminSystemPositionGetPathParams, AdminSystemPositionGetQueryResponse } from '../../models/AdminSystemPositionGet';

import { createCommonResFaker } from '../createCommonResFaker';
import { createPositionResFaker } from '../createPositionResFaker';

export function createAdminSystemPositionGetPathParamsFaker(data?: Partial<AdminSystemPositionGetPathParams>): AdminSystemPositionGetPathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description success
 */
export function createAdminSystemPositionGet200Faker(data?: Partial<AdminSystemPositionGet200>): AdminSystemPositionGet200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: createPositionResFaker() });
}

export function createAdminSystemPositionGetQueryResponseFaker(data?: Partial<AdminSystemPositionGetQueryResponse>): AdminSystemPositionGetQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemPositionGet200Faker()]);
}
