/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemPositionsDelete200, AdminSystemPositionsDeleteMutationResponse } from '../../models/AdminSystemPositionsDelete';

import { createCommonResFaker } from '../createCommonResFaker';
import { createIdsReqFaker } from '../createIdsReqFaker';

/**
 * @description 非查询返回
 */
export function createAdminSystemPositionsDelete200Faker(data?: Partial<AdminSystemPositionsDelete200>): AdminSystemPositionsDelete200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: faker.string.alpha() });
}

export function createAdminSystemPositionsDeleteMutationRequestFaker() {
  faker.seed([2021]);
  return createIdsReqFaker();
}

export function createAdminSystemPositionsDeleteMutationResponseFaker(
  data?: Partial<AdminSystemPositionsDeleteMutationResponse>,
): AdminSystemPositionsDeleteMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemPositionsDelete200Faker()]);
}
