/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type {
  AdminSystemPositionsQuery200,
  AdminSystemPositionsQueryQueryParams,
  AdminSystemPositionsQueryQueryResponse,
} from '../../models/AdminSystemPositionsQuery';

import { createCommonPageResFaker } from '../createCommonPageResFaker';
import { createCommonResFaker } from '../createCommonResFaker';
import { createPositionResFaker } from '../createPositionResFaker';

export function createAdminSystemPositionsQueryQueryParamsFaker(data?: Partial<AdminSystemPositionsQueryQueryParams>): AdminSystemPositionsQueryQueryParams {
  faker.seed([2021]);
  return {
    ...{
      page_no: 1,
      page_size: 10,
      created_at: faker.helpers.multiple(() => faker.number.int(), { count: { min: 0, max: 2 } }),
      updated_at: faker.helpers.multiple(() => faker.number.int(), { count: { min: 0, max: 2 } }),
      position_name: faker.string.alpha(),
      code: '000000',
    },
    ...(data || {}),
  };
}

/**
 * @description success
 */
export function createAdminSystemPositionsQuery200Faker(data?: Partial<AdminSystemPositionsQuery200>): AdminSystemPositionsQuery200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), {
    data: Object.assign({}, createCommonPageResFaker(), { list: faker.helpers.multiple(() => createPositionResFaker()) }),
  });
}

export function createAdminSystemPositionsQueryQueryResponseFaker(
  data?: Partial<AdminSystemPositionsQueryQueryResponse>,
): AdminSystemPositionsQueryQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemPositionsQuery200Faker()]);
}
