/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type {
  AdminSystemPositionPost200,
  AdminSystemPositionPostMutationRequest,
  AdminSystemPositionPostMutationResponse,
} from '../../models/AdminSystemPositionPost';

import { createCommonResFaker } from '../createCommonResFaker';

/**
 * @description 非查询返回
 */
export function createAdminSystemPositionPost200Faker(data?: Partial<AdminSystemPositionPost200>): AdminSystemPositionPost200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: faker.string.alpha() });
}

export function createAdminSystemPositionPostMutationRequestFaker(
  data?: Partial<AdminSystemPositionPostMutationRequest>,
): AdminSystemPositionPostMutationRequest {
  faker.seed([2021]);
  return {
    ...{ sort: faker.number.int({ min: 0 }), position_name: faker.string.alpha({ length: 255 }), code: '000000', remark: faker.string.alpha({ length: 255 }) },
    ...(data || {}),
  };
}

export function createAdminSystemPositionPostMutationResponseFaker(
  data?: Partial<AdminSystemPositionPostMutationResponse>,
): AdminSystemPositionPostMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemPositionPost200Faker()]);
}
