/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type {
  AdminSystemPositionPut200,
  AdminSystemPositionPutMutationRequest,
  AdminSystemPositionPutMutationResponse,
  AdminSystemPositionPutPathParams,
} from '../../models/AdminSystemPositionPut';

import { createCommonResFaker } from '../createCommonResFaker';

export function createAdminSystemPositionPutPathParamsFaker(data?: Partial<AdminSystemPositionPutPathParams>): AdminSystemPositionPutPathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description 非查询返回
 */
export function createAdminSystemPositionPut200Faker(data?: Partial<AdminSystemPositionPut200>): AdminSystemPositionPut200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: faker.string.alpha() });
}

export function createAdminSystemPositionPutMutationRequestFaker(data?: Partial<AdminSystemPositionPutMutationRequest>): AdminSystemPositionPutMutationRequest {
  faker.seed([2021]);
  return {
    ...{ sort: faker.number.int({ min: 0 }), position_name: faker.string.alpha({ length: 255 }), code: '000000', remark: faker.string.alpha({ length: 255 }) },
    ...(data || {}),
  };
}

export function createAdminSystemPositionPutMutationResponseFaker(
  data?: Partial<AdminSystemPositionPutMutationResponse>,
): AdminSystemPositionPutMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemPositionPut200Faker()]);
}
