/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { accountLoginPassword } from './accountLoginPassword';
import { accountRefresh } from './accountRefresh';

export function accountService() {
  return { accountLoginPassword, accountRefresh };
}
