/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AccountLogoutMutationRequest, AccountLogoutMutationResponse } from '../../models/AccountLogout';

import { accountLogoutMutationRequestSchema, accountLogoutMutationResponseSchema } from '../../zod/accountController/accountLogoutSchema';

export function getAccountLogoutUrl() {
  return `/api/v1/admin_system/account/logout` as const;
}

/**
 * @summary 登出
 * {@link /api/v1/admin_system/account/logout}
 */
export async function accountLogout(
  { data }: { data?: AccountLogoutMutationRequest },
  config: Partial<RequestConfig<AccountLogoutMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = accountLogoutMutationRequestSchema.parse(data);
  const res = await request<AccountLogoutMutationResponse, ResponseErrorConfig<Error>, AccountLogoutMutationRequest>({
    method: 'POST',
    url: getAccountLogoutUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: accountLogoutMutationResponseSchema.parse(res.data) };
}
