/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AccountRefreshMutationRequest, AccountRefreshMutationResponse } from '../../models/AccountRefresh';

import { accountRefreshMutationRequestSchema, accountRefreshMutationResponseSchema } from '../../zod/accountController/accountRefreshSchema';

export function getAccountRefreshUrl() {
  return `/api/v1/admin_system/account/refresh` as const;
}

/**
 * @description 使用refresh_token刷新access_token
 * @summary 刷新access_token
 * {@link /api/v1/admin_system/account/refresh}
 */
export async function accountRefresh(
  { data }: { data: AccountRefreshMutationRequest },
  config: Partial<RequestConfig<AccountRefreshMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = accountRefreshMutationRequestSchema.parse(data);
  const res = await request<AccountRefreshMutationResponse, ResponseErrorConfig<Error>, AccountRefreshMutationRequest>({
    method: 'POST',
    url: getAccountRefreshUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: accountRefreshMutationResponseSchema.parse(res.data) };
}
