/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/utils/ky-client';

import fetch from '@/utils/ky-client';

import type { AccountLoginPasswordMutationRequest, AccountLoginPasswordMutationResponse } from '../../models/AccountLoginPassword';

import { accountLoginPasswordMutationRequestSchema, accountLoginPasswordMutationResponseSchema } from '../../zod/accountController/accountLoginPasswordSchema';

export function getAccountLoginPasswordUrl() {
  return `/api/v1/admin_system/account/login_password` as const;
}

/**
 * @summary 使用邮箱密码登录
 * {@link /api/v1/admin_system/account/login_password}
 */
export async function accountLoginPassword(
  { data }: { data: AccountLoginPasswordMutationRequest },
  config: Partial<RequestConfig<AccountLoginPasswordMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = accountLoginPasswordMutationRequestSchema.parse(data);
  const res = await request<AccountLoginPasswordMutationResponse, ResponseErrorConfig<Error>, AccountLoginPasswordMutationRequest>({
    method: 'POST',
    url: getAccountLoginPasswordUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: accountLoginPasswordMutationResponseSchema.parse(res.data) };
}
