/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { accountLoginPassword } from './accountLoginPassword';

export function accountService() {
  return { accountLoginPassword };
}
