/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemMenuDeleteMutationResponse } from '../../models/AdminSystemMenuDelete';

import { createAdminSystemMenuDeleteMutationResponseFaker } from '../../mocks/menuController/createAdminSystemMenuDeleteFaker';

export function adminSystemMenuDeleteHandler(
  data?: AdminSystemMenuDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response),
) {
  return http.delete('/api/v1/admin_system/manu/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemMenuDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
