/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemMenuPutMutationResponse } from '../../models/AdminSystemMenuPut';

import { createAdminSystemMenuPutMutationResponseFaker } from '../../mocks/menuController/createAdminSystemMenuPutFaker';

export function adminSystemMenuPutHandler(data?: AdminSystemMenuPutMutationResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Response)) {
  return http.put('/api/v1/admin_system/manu/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemMenuPutMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
