/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemMenusDeleteMutationResponse } from '../../models/AdminSystemMenusDelete';

import { createAdminSystemMenusDeleteMutationResponseFaker } from '../../mocks/menuController/createAdminSystemMenusDeleteFaker';

export function adminSystemMenusDeleteHandler(
  data?: AdminSystemMenusDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
  return http.post('/api/v1/admin_system/menu/delete', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemMenusDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
