/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemMenuPostMutationResponse } from '../../models/AdminSystemMenuPost';

import { createAdminSystemMenuPostMutationResponseFaker } from '../../mocks/menuController/createAdminSystemMenuPostFaker';

export function adminSystemMenuPostHandler(data?: AdminSystemMenuPostMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response)) {
  return http.post('/api/v1/admin_system/menu', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemMenuPostMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
