/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemMenuGetQueryResponse } from '../../models/AdminSystemMenuGet';

import { createAdminSystemMenuGetQueryResponseFaker } from '../../mocks/menuController/createAdminSystemMenuGetFaker';

export function adminSystemMenuGetHandler(data?: AdminSystemMenuGetQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response)) {
  return http.get('/api/v1/admin_system/manu/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemMenuGetQueryResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
