/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type {
  AdminSystemUserGetByEmail200,
  AdminSystemUserGetByEmailQueryParams,
  AdminSystemUserGetByEmailQueryResponse,
} from '../../models/AdminSystemUserGetByEmail';

import { createCommonResFaker } from '../createCommonResFaker';
import { createUserResFaker } from '../createUserResFaker';

export function createAdminSystemUserGetByEmailQueryParamsFaker(data?: Partial<AdminSystemUserGetByEmailQueryParams>): AdminSystemUserGetByEmailQueryParams {
  faker.seed([2021]);
  return {
    ...{ email: faker.internet.email() },
    ...(data || {}),
  };
}

/**
 * @description success
 */
export function createAdminSystemUserGetByEmail200Faker(data?: Partial<AdminSystemUserGetByEmail200>): AdminSystemUserGetByEmail200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: createUserResFaker() });
}

export function createAdminSystemUserGetByEmailQueryResponseFaker(
  data?: Partial<AdminSystemUserGetByEmailQueryResponse>,
): AdminSystemUserGetByEmailQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemUserGetByEmail200Faker()]);
}
