/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemUserGet200, AdminSystemUserGetPathParams, AdminSystemUserGetQueryResponse } from '../../models/AdminSystemUserGet';

import { createCommonResFaker } from '../createCommonResFaker';
import { createUserResFaker } from '../createUserResFaker';

export function createAdminSystemUserGetPathParamsFaker(data?: Partial<AdminSystemUserGetPathParams>): AdminSystemUserGetPathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description success
 */
export function createAdminSystemUserGet200Faker(data?: Partial<AdminSystemUserGet200>): AdminSystemUserGet200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: createUserResFaker() });
}

export function createAdminSystemUserGetQueryResponseFaker(data?: Partial<AdminSystemUserGetQueryResponse>): AdminSystemUserGetQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemUserGet200Faker()]);
}
