/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemUsersDelete200, AdminSystemUsersDeleteMutationResponse } from '../../models/AdminSystemUsersDelete';

import { createCommonResFaker } from '../createCommonResFaker';
import { createIdsReqFaker } from '../createIdsReqFaker';

/**
 * @description 非查询返回
 */
export function createAdminSystemUsersDelete200Faker(data?: Partial<AdminSystemUsersDelete200>): AdminSystemUsersDelete200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: faker.string.alpha() });
}

export function createAdminSystemUsersDeleteMutationRequestFaker() {
  faker.seed([2021]);
  return createIdsReqFaker();
}

export function createAdminSystemUsersDeleteMutationResponseFaker(
  data?: Partial<AdminSystemUsersDeleteMutationResponse>,
): AdminSystemUsersDeleteMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemUsersDelete200Faker()]);
}
