/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemUsersQuery200, AdminSystemUsersQueryQueryParams, AdminSystemUsersQueryQueryResponse } from '../../models/AdminSystemUsersQuery';

import { createCommonPageResFaker } from '../createCommonPageResFaker';
import { createCommonResFaker } from '../createCommonResFaker';
import { createUserResFaker } from '../createUserResFaker';

export function createAdminSystemUsersQueryQueryParamsFaker(data?: Partial<AdminSystemUsersQueryQueryParams>): AdminSystemUsersQueryQueryParams {
  faker.seed([2021]);
  return {
    ...{
      page_no: 1,
      page_size: 10,
      created_at: faker.helpers.multiple(() => faker.number.int(), { count: { min: 0, max: 2 } }),
      updated_at: faker.helpers.multiple(() => faker.number.int(), { count: { min: 0, max: 2 } }),
      status: faker.helpers.arrayElement<NonNullable<AdminSystemUsersQueryQueryParams>['status']>([1, 2]),
      email: faker.internet.email(),
      name: faker.string.alpha(),
      nickname: faker.string.alpha(),
      phone: '18688886666',
      department_ids: faker.helpers.multiple(() => faker.string.alpha()),
      position_ids: faker.helpers.multiple(() => faker.string.alpha()),
      role_ids: faker.helpers.multiple(() => faker.string.alpha()),
    },
    ...(data || {}),
  };
}

/**
 * @description success
 */
export function createAdminSystemUsersQuery200Faker(data?: Partial<AdminSystemUsersQuery200>): AdminSystemUsersQuery200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), {
    result: Object.assign({}, createCommonPageResFaker(), { list: faker.helpers.multiple(() => createUserResFaker()) }),
  });
}

export function createAdminSystemUsersQueryQueryResponseFaker(data?: Partial<AdminSystemUsersQueryQueryResponse>): AdminSystemUsersQueryQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemUsersQuery200Faker()]);
}
