/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemUserDelete200, AdminSystemUserDeleteMutationResponse, AdminSystemUserDeletePathParams } from '../../models/AdminSystemUserDelete';

import { createCommonResFaker } from '../createCommonResFaker';
import { createEmptyResFaker } from '../createEmptyResFaker';

export function createAdminSystemUserDeletePathParamsFaker(data?: Partial<AdminSystemUserDeletePathParams>): AdminSystemUserDeletePathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description 非查询返回
 */
export function createAdminSystemUserDelete200Faker(data?: Partial<AdminSystemUserDelete200>): AdminSystemUserDelete200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: faker.string.alpha() });
}

export function createAdminSystemUserDeleteMutationRequestFaker() {
  faker.seed([2021]);
  return createEmptyResFaker();
}

export function createAdminSystemUserDeleteMutationResponseFaker(data?: Partial<AdminSystemUserDeleteMutationResponse>): AdminSystemUserDeleteMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemUserDelete200Faker()]);
}
