/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemUserPost200, AdminSystemUserPostMutationRequest, AdminSystemUserPostMutationResponse } from '../../models/AdminSystemUserPost';

import { createCommonResFaker } from '../createCommonResFaker';

/**
 * @description 非查询返回
 */
export function createAdminSystemUserPost200Faker(data?: Partial<AdminSystemUserPost200>): AdminSystemUserPost200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: faker.string.alpha() });
}

export function createAdminSystemUserPostMutationRequestFaker(data?: Partial<AdminSystemUserPostMutationRequest>): AdminSystemUserPostMutationRequest {
  faker.seed([2021]);
  return {
    ...{
      password: faker.string.alpha({ length: 6 }),
      confirm: faker.string.alpha({ length: 6 }),
      email: faker.internet.email(),
      name: faker.string.alpha({ length: 255 }),
      nickname: faker.string.alpha({ length: 255 }),
      phone: '18688886666',
      avatar: faker.image.avatar(),
      remark: faker.string.alpha({ length: 255 }),
      department_id: faker.string.alpha({ length: { min: 20, max: 20 } }),
      position_ids: faker.helpers.multiple(() => faker.string.alpha()),
      role_ids: faker.helpers.multiple(() => faker.string.alpha()),
    },
    ...(data || {}),
  };
}

export function createAdminSystemUserPostMutationResponseFaker(data?: Partial<AdminSystemUserPostMutationResponse>): AdminSystemUserPostMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemUserPost200Faker()]);
}
