/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { BaseInitMutationResponse } from '../../models/BaseInit';

import { createBaseInitMutationResponseFaker } from '../../mocks/systemController/createBaseInitFaker';

export function baseInitHandler(data?: BaseInitMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response)) {
  return http.post('/api/v1/admin_system/base/init', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createBaseInitMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
