/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type {
  AdminSystemMenuPut200,
  AdminSystemMenuPutMutationRequest,
  AdminSystemMenuPutMutationResponse,
  AdminSystemMenuPutPathParams,
} from '../../models/AdminSystemMenuPut';

import { createCommonResFaker } from '../createCommonResFaker';
import { createResourceFaker } from '../createResourceFaker';

export function createAdminSystemMenuPutPathParamsFaker(data?: Partial<AdminSystemMenuPutPathParams>): AdminSystemMenuPutPathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description 非查询返回
 */
export function createAdminSystemMenuPut200Faker(data?: Partial<AdminSystemMenuPut200>): AdminSystemMenuPut200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: faker.string.alpha() });
}

export function createAdminSystemMenuPutMutationRequestFaker(data?: Partial<AdminSystemMenuPutMutationRequest>): AdminSystemMenuPutMutationRequest {
  faker.seed([2021]);
  return {
    ...{
      sort: faker.number.int({ min: 0 }),
      status: faker.helpers.arrayElement<NonNullable<AdminSystemMenuPutMutationRequest>['status']>([1, 2]),
      title: faker.string.alpha({ length: 255 }),
      icon: faker.string.alpha({ length: 512 }),
      properties: faker.string.alpha({ length: 2048 }),
      resources: faker.helpers.multiple(() => createResourceFaker()),
    },
    ...(data || {}),
  };
}

export function createAdminSystemMenuPutMutationResponseFaker(data?: Partial<AdminSystemMenuPutMutationResponse>): AdminSystemMenuPutMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemMenuPut200Faker()]);
}
