/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemMenuPost200, AdminSystemMenuPostMutationRequest, AdminSystemMenuPostMutationResponse } from '../../models/AdminSystemMenuPost';

import { createCommonResFaker } from '../createCommonResFaker';
import { createResourceFaker } from '../createResourceFaker';

/**
 * @description 非查询返回
 */
export function createAdminSystemMenuPost200Faker(data?: Partial<AdminSystemMenuPost200>): AdminSystemMenuPost200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: faker.string.alpha() });
}

export function createAdminSystemMenuPostMutationRequestFaker(data?: Partial<AdminSystemMenuPostMutationRequest>): AdminSystemMenuPostMutationRequest {
  faker.seed([2021]);
  return {
    ...{
      sort: faker.number.int({ min: 0 }),
      title: faker.string.alpha({ length: 255 }),
      icon: faker.string.alpha({ length: 512 }),
      code: '000000',
      parent_id: faker.string.alpha({ length: { min: 20, max: 20 } }),
      menu_type: faker.helpers.arrayElement<NonNullable<AdminSystemMenuPostMutationRequest>['menu_type']>(['page', 'button']),
      menu_path: faker.string.alpha({ length: 255 }),
      properties: faker.string.alpha({ length: 2048 }),
      resources: faker.helpers.multiple(() => createResourceFaker()),
    },
    ...(data || {}),
  };
}

export function createAdminSystemMenuPostMutationResponseFaker(data?: Partial<AdminSystemMenuPostMutationResponse>): AdminSystemMenuPostMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemMenuPost200Faker()]);
}
