/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemMenuGet200, AdminSystemMenuGetPathParams, AdminSystemMenuGetQueryResponse } from '../../models/AdminSystemMenuGet';

import { createCommonResFaker } from '../createCommonResFaker';
import { createMenuResFaker } from '../createMenuResFaker';

export function createAdminSystemMenuGetPathParamsFaker(data?: Partial<AdminSystemMenuGetPathParams>): AdminSystemMenuGetPathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description success
 */
export function createAdminSystemMenuGet200Faker(data?: Partial<AdminSystemMenuGet200>): AdminSystemMenuGet200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: createMenuResFaker() });
}

export function createAdminSystemMenuGetQueryResponseFaker(data?: Partial<AdminSystemMenuGetQueryResponse>): AdminSystemMenuGetQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemMenuGet200Faker()]);
}
