/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemMenusDelete200, AdminSystemMenusDeleteMutationResponse } from '../../models/AdminSystemMenusDelete';

import { createCommonResFaker } from '../createCommonResFaker';
import { createIdsReqFaker } from '../createIdsReqFaker';

/**
 * @description 非查询返回
 */
export function createAdminSystemMenusDelete200Faker(data?: Partial<AdminSystemMenusDelete200>): AdminSystemMenusDelete200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: faker.string.alpha() });
}

export function createAdminSystemMenusDeleteMutationRequestFaker() {
  faker.seed([2021]);
  return createIdsReqFaker();
}

export function createAdminSystemMenusDeleteMutationResponseFaker(
  data?: Partial<AdminSystemMenusDeleteMutationResponse>,
): AdminSystemMenusDeleteMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemMenusDelete200Faker()]);
}
