/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemMenuDelete200, AdminSystemMenuDeleteMutationResponse, AdminSystemMenuDeletePathParams } from '../../models/AdminSystemMenuDelete';

import { createCommonResFaker } from '../createCommonResFaker';
import { createEmptyResFaker } from '../createEmptyResFaker';

export function createAdminSystemMenuDeletePathParamsFaker(data?: Partial<AdminSystemMenuDeletePathParams>): AdminSystemMenuDeletePathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description 非查询返回
 */
export function createAdminSystemMenuDelete200Faker(data?: Partial<AdminSystemMenuDelete200>): AdminSystemMenuDelete200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: faker.string.alpha() });
}

export function createAdminSystemMenuDeleteMutationRequestFaker() {
  faker.seed([2021]);
  return createEmptyResFaker();
}

export function createAdminSystemMenuDeleteMutationResponseFaker(data?: Partial<AdminSystemMenuDeleteMutationResponse>): AdminSystemMenuDeleteMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemMenuDelete200Faker()]);
}
