/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemMenusQuery200, AdminSystemMenusQueryQueryResponse } from '../../models/AdminSystemMenusQuery';

import { createCommonResFaker } from '../createCommonResFaker';
import { createMenuResFaker } from '../createMenuResFaker';

/**
 * @description success
 */
export function createAdminSystemMenusQuery200Faker(data?: Partial<AdminSystemMenusQuery200>): AdminSystemMenusQuery200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: { list: faker.helpers.multiple(() => createMenuResFaker()) } });
}

export function createAdminSystemMenusQueryQueryResponseFaker(data?: Partial<AdminSystemMenusQueryQueryResponse>): AdminSystemMenusQueryQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemMenusQuery200Faker()]);
}
