/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { positionResSchema } from '../positionResSchema';

export const adminSystemPositionGetPathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemPositionGetPathParamsSchema = z.infer<typeof adminSystemPositionGetPathParamsSchema>;

/**
 * @description success
 */
export const adminSystemPositionGet200Schema = commonResSchema.and(
  z.object({
    get result() {
      return positionResSchema;
    },
  }),
);

export type AdminSystemPositionGet200Schema = z.infer<typeof adminSystemPositionGet200Schema>;

export const adminSystemPositionGetQueryResponseSchema = adminSystemPositionGet200Schema;

export type AdminSystemPositionGetQueryResponseSchema = z.infer<typeof adminSystemPositionGetQueryResponseSchema>;
