/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonPageResSchema } from '../commonPageResSchema';
import { commonResSchema } from '../commonResSchema';
import { positionResSchema } from '../positionResSchema';

export const adminSystemPositionsQueryQueryParamsSchema = z
  .object({
    page_no: z.coerce.number().int().min(0).optional(),
    page_size: z.coerce.number().int().min(0).optional(),
    created_at: z.array(z.coerce.number().int()).max(2).optional(),
    updated_at: z.array(z.coerce.number().int()).max(2).optional(),
    position_name: z.string().optional(),
    code: z.string().optional(),
  })
  .optional();

export type AdminSystemPositionsQueryQueryParamsSchema = z.infer<typeof adminSystemPositionsQueryQueryParamsSchema>;

/**
 * @description success
 */
export const adminSystemPositionsQuery200Schema = commonResSchema.and(
  z.object({
    get data() {
      return commonPageResSchema.and(
        z.object({
          get list() {
            return z.array(positionResSchema);
          },
        }),
      );
    },
  }),
);

export type AdminSystemPositionsQuery200Schema = z.infer<typeof adminSystemPositionsQuery200Schema>;

export const adminSystemPositionsQueryQueryResponseSchema = adminSystemPositionsQuery200Schema;

export type AdminSystemPositionsQueryQueryResponseSchema = z.infer<typeof adminSystemPositionsQueryQueryResponseSchema>;
