/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { idsReqSchema } from '../idsReqSchema';

/**
 * @description 非查询返回
 */
export const adminSystemPositionsDelete200Schema = commonResSchema.and(
  z.object({
    result: z.string(),
  }),
);

export type AdminSystemPositionsDelete200Schema = z.infer<typeof adminSystemPositionsDelete200Schema>;

export const adminSystemPositionsDeleteMutationRequestSchema = idsReqSchema;

export type AdminSystemPositionsDeleteMutationRequestSchema = z.infer<typeof adminSystemPositionsDeleteMutationRequestSchema>;

export const adminSystemPositionsDeleteMutationResponseSchema = adminSystemPositionsDelete200Schema;

export type AdminSystemPositionsDeleteMutationResponseSchema = z.infer<typeof adminSystemPositionsDeleteMutationResponseSchema>;
