/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';

/**
 * @description 非查询返回
 */
export const adminSystemPositionPost200Schema = commonResSchema.and(
  z.object({
    data: z.string(),
  }),
);

export type AdminSystemPositionPost200Schema = z.infer<typeof adminSystemPositionPost200Schema>;

export const adminSystemPositionPostMutationRequestSchema = z.object({
  sort: z.int().min(0).optional(),
  position_name: z.string().max(255),
  code: z.string().max(255),
  remark: z.string().max(255).optional(),
});

export type AdminSystemPositionPostMutationRequestSchema = z.infer<typeof adminSystemPositionPostMutationRequestSchema>;

export const adminSystemPositionPostMutationResponseSchema = adminSystemPositionPost200Schema;

export type AdminSystemPositionPostMutationResponseSchema = z.infer<typeof adminSystemPositionPostMutationResponseSchema>;
