/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { emptyResSchema } from '../emptyResSchema';

export const adminSystemPositionDeletePathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemPositionDeletePathParamsSchema = z.infer<typeof adminSystemPositionDeletePathParamsSchema>;

/**
 * @description 非查询返回
 */
export const adminSystemPositionDelete200Schema = commonResSchema.and(
  z.object({
    data: z.string(),
  }),
);

export type AdminSystemPositionDelete200Schema = z.infer<typeof adminSystemPositionDelete200Schema>;

export const adminSystemPositionDeleteMutationRequestSchema = emptyResSchema;

export type AdminSystemPositionDeleteMutationRequestSchema = z.infer<typeof adminSystemPositionDeleteMutationRequestSchema>;

export const adminSystemPositionDeleteMutationResponseSchema = adminSystemPositionDelete200Schema;

export type AdminSystemPositionDeleteMutationResponseSchema = z.infer<typeof adminSystemPositionDeleteMutationResponseSchema>;
