// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "login": {
    "meta": {
      "title": "登录",
      "description": ""
    },
    "page": {
      "h1": "大型中后台管理系统",
      "sub": "这是副标题或者一段说明文字",
      "welcome": "欢迎使用",
      "explain": "使用邮箱和密码进行登录",
      "emailPlaceholder": "邮箱",
      "passwdPlaceholder": "密码",
      "submit": "登录"
    }
  },
  "app": {
    "404": {
      "title": "页面不存在",
      "content": "抱歉，你访问的页面不存在或已被删除。",
      "home": "前往首页",
      "back": "返回"
    },
    "500": {
      "title": "系统错误",
      "content": "如果持续出现错误，请联系管理员",
      "retry": "重试",
      "home": "前往首页"
    },
    "title": "CyberEcosystem",
    "template": "%s - CyberEcosystem",
    "description": "",
    "applicationName": "",
    "keywords": "",
    "switcher": {
      "locale": "{locale, select, zh_CN {简体中文} ar_EG {العربية} other {Unknown}}"
    },
    "error": {
      "unknown": "未知网络错误",
      "abort": "取消网络请求",
      "timeout": "网络请求超时",
      "http": "未知请求错误",
      "zod": "参数或返回值校验失败",
      "zodField": "以下字段校验失败: {fields}"
    },
    "request_toast": {
      "loading": "请求中...",
      "success": "请求成功",
      "error": "请求失败"
    }
  }
};
export default messages;