// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "app": {
    "404": {
      "title": "页面不存在",
      "content": "抱歉，你访问的页面不存在或已被删除。",
      "home": "前往首页",
      "back": "返回"
    },
    "500": {
      "title": "系统错误",
      "content": "如果持续出现错误，请联系管理员",
      "retry": "重试",
      "home": "前往首页"
    },
    "title": "CyberEcosystem",
    "template": "%s - CyberEcosystem",
    "description": "",
    "applicationName": "",
    "keywords": "",
    "switcher": {
      "locale": "{locale, select, zh_CN {简体中文} ar_EG {العربية} other {Unknown}}"
    }
  }
};
export default messages;