// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "setting": {
    "drawer": {
      "title": "偏好设置",
      "reset": "重置",
      "segment1": "基本",
      "segment2": "布局",
      "segment3": "快捷键",
      "segment4": "其他",
      "language": "语言",
      "light-dark": "明暗模式",
      "light": "明亮",
      "dark": "暗黑",
      "system": "跟随系统",
      "aside-dark": "深色侧边栏",
      "top-dark": "深色顶栏",
      "primary": "主题色",
      "#f43f5e": "玫瑰红",
      "#fb7185": "火烈鸟粉",
      "#fb923c": "橙色",
      "#facc15": "金黄",
      "#a3e635": "青柠绿",
      "#4ade80": "祖母绿",
      "#14b8a6": "蓝绿",
      "#0ea5e9": "天空蓝",
      "#22d3ee": "青色",
      "#1677ff": "亮蓝",
      "#6366f1": "靛蓝",
      "#8b5cf6": "紫罗兰",
      "#c084fc": "兰花紫",
      "#ec4899": "洋红",
      "#94a3b8": "石板灰",
      "layout": "布局",
      "vertical": "垂直",
      "two-vertical": "双列垂直",
      "horizontal": "水平",
      "aside-vertical": "侧边栏",
      "mixed-vertical": "混合垂直",
      "mixed-two-vertical": "混合双列",
      "content": "内容",
      "wide": "流式",
      "fixed": "定宽",
      "shortcut": "快捷键",
      "shortcut-logout": "退出登录",
      "shortcut-lock": "锁定屏幕",
      "watermark": "水印"
    }
  },
  "login": {
    "meta": {
      "title": "登录",
      "description": ""
    },
    "page": {
      "h1": "大型中后台管理系统",
      "sub": "这是副标题或者一段说明文字",
      "welcome": "欢迎使用",
      "explain": "使用邮箱和密码进行登录",
      "emailPlaceholder": "邮箱",
      "passwdPlaceholder": "密码",
      "submit": "登录"
    },
    "toast": {
      "email": "邮箱",
      "passwd": "密码",
      "loginSuccess": "登录成功"
    },
    "menu": {
      "lock": "锁定屏幕",
      "logout": "退出登录"
    }
  },
  "app": {
    "404": {
      "title": "页面不存在",
      "content": "抱歉，你访问的页面不存在或已被删除。",
      "home": "前往首页",
      "back": "返回"
    },
    "500": {
      "title": "系统错误",
      "content": "如果持续出现错误，请联系管理员",
      "retry": "重试",
      "home": "前往首页"
    },
    "title": "CyberEcosystem",
    "template": "%s - CyberEcosystem",
    "description": "",
    "applicationName": "",
    "keywords": "",
    "switcher": {
      "locale": "{locale, select, zh_CN {简体中文} ar_EG {العربية} other {Unknown}}"
    },
    "error": {
      "unknown": "未知网络错误",
      "abort": "取消网络请求",
      "timeout": "网络请求超时",
      "http": "未知请求错误",
      "zod": "参数或返回值校验失败",
      "zodField": "{fields}: 校验失败"
    },
    "request_toast": {
      "loading": "请求中...",
      "success": "请求成功",
      "error": "请求失败"
    }
  }
};
export default messages;