/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { JwtResponse } from './JwtResponse';

/**
 * @description success
 */
export type AccountRefresh200 = CommonRes & {
  /**
   * @type object
   */
  data: JwtResponse;
};

export interface AccountRefreshMutationRequest {
  /**
   * @type string
   */
  refresh_token: string;
}

export type AccountRefreshMutationResponse = AccountRefresh200;

export interface AccountRefreshMutation {
  Response: AccountRefresh200;
  Request: AccountRefreshMutationRequest;
  Errors: any;
}
