/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { JwtResponse } from './JwtResponse';

/**
 * @description success
 */
export type AccountLoginPassword200 = CommonRes & {
  /**
   * @type object
   */
  result: JwtResponse;
};

export interface AccountLoginPasswordMutationRequest {
  /**
   * @description 邮箱
   * @type string, email
   */
  email: string;
  /**
   * @description 密码
   * @minLength 6
   * @maxLength 20
   * @type string, password
   */
  password: string;
}

export type AccountLoginPasswordMutationResponse = AccountLoginPassword200;

export interface AccountLoginPasswordMutation {
  Response: AccountLoginPassword200;
  Request: AccountLoginPasswordMutationRequest;
  Errors: any;
}
