/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { EmptyRes } from './EmptyRes';

/**
 * @description success
 */
export type AccountLogout200 = CommonRes;

export type AccountLogoutMutationRequest = EmptyRes;

export type AccountLogoutMutationResponse = AccountLogout200;

export interface AccountLogoutMutation {
  Response: AccountLogout200;
  Request: AccountLogoutMutationRequest;
  Errors: any;
}
