/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';

export interface AdminSystemUserPutPathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemUserPut200 = CommonRes & {
  /**
   * @type string
   */
  data: string;
};

export const adminSystemUserPutMutationRequestStatusEnum = {
  1: 1,
  2: 2,
} as const;

export type AdminSystemUserPutMutationRequestStatusEnum
  = (typeof adminSystemUserPutMutationRequestStatusEnum)[keyof typeof adminSystemUserPutMutationRequestStatusEnum];

export interface AdminSystemUserPutMutationRequest {
  /**
   * @type integer | undefined, int8
   */
  status?: AdminSystemUserPutMutationRequestStatusEnum;
  /**
   * @minLength 6
   * @type string | undefined
   */
  password?: string;
  /**
   * @minLength 6
   * @type string | undefined
   */
  confirm?: string;
  /**
   * @maxLength 255
   * @type string | undefined, email
   */
  email?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  name?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  nickname?: string;
  /**
   * @pattern ^[0-9]+$
   * @type string | undefined
   */
  phone?: string;
  /**
   * @maxLength 1024
   * @type string | undefined
   */
  avatar?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  remark?: string;
  /**
   * @minLength 20
   * @maxLength 20
   * @type string | undefined
   */
  department_id?: string;
  /**
   * @type array | undefined
   */
  position_ids?: string[];
  /**
   * @type array | undefined
   */
  role_ids?: string[];
}

export type AdminSystemUserPutMutationResponse = AdminSystemUserPut200;

export interface AdminSystemUserPutMutation {
  Response: AdminSystemUserPut200;
  Request: AdminSystemUserPutMutationRequest;
  PathParams: AdminSystemUserPutPathParams;
  Errors: any;
}
