/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { EmptyRes } from './EmptyRes';

export interface AdminSystemPositionDeletePathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemPositionDelete200 = CommonRes & {
  /**
   * @type string
   */
  data: string;
};

export type AdminSystemPositionDeleteMutationRequest = EmptyRes;

export type AdminSystemPositionDeleteMutationResponse = AdminSystemPositionDelete200;

export interface AdminSystemPositionDeleteMutation {
  Response: AdminSystemPositionDelete200;
  Request: AdminSystemPositionDeleteMutationRequest;
  PathParams: AdminSystemPositionDeletePathParams;
  Errors: any;
}
