/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';

export interface AdminSystemPositionPutPathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemPositionPut200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export interface AdminSystemPositionPutMutationRequest {
  /**
   * @minLength 0
   * @type integer | undefined, int32
   */
  sort?: number;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  position_name?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  code?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  remark?: string;
}

export type AdminSystemPositionPutMutationResponse = AdminSystemPositionPut200;

export interface AdminSystemPositionPutMutation {
  Response: AdminSystemPositionPut200;
  Request: AdminSystemPositionPutMutationRequest;
  PathParams: AdminSystemPositionPutPathParams;
  Errors: any;
}
