/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonPageRes } from './CommonPageRes';
import type { CommonRes } from './CommonRes';
import type { PositionRes } from './PositionRes';

export interface AdminSystemPositionsQueryQueryParams {
  /**
   * @minLength 0
   * @type integer | undefined, int64
   */
  page_no?: number;
  /**
   * @minLength 0
   * @type integer | undefined, int64
   */
  page_size?: number;
  /**
   * @type array | undefined
   */
  created_at?: number[];
  /**
   * @type array | undefined
   */
  updated_at?: number[];
  /**
   * @type string | undefined
   */
  position_name?: string;
  /**
   * @type string | undefined
   */
  code?: string;
}

/**
 * @description success
 */
export type AdminSystemPositionsQuery200 = CommonRes & {
  result: CommonPageRes & {
    /**
     * @type array
     */
    list: PositionRes[];
  };
};

export type AdminSystemPositionsQueryQueryResponse = AdminSystemPositionsQuery200;

export interface AdminSystemPositionsQueryQuery {
  Response: AdminSystemPositionsQuery200;
  QueryParams: AdminSystemPositionsQueryQueryParams;
  Errors: any;
}
