/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { Resource } from './Resource';

export interface AdminSystemMenuPutPathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemMenuPut200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export const adminSystemMenuPutMutationRequestStatusEnum = {
  1: 1,
  2: 2,
} as const;

export type AdminSystemMenuPutMutationRequestStatusEnum
  = (typeof adminSystemMenuPutMutationRequestStatusEnum)[keyof typeof adminSystemMenuPutMutationRequestStatusEnum];

export interface AdminSystemMenuPutMutationRequest {
  /**
   * @minLength 0
   * @type integer | undefined, int32
   */
  sort?: number;
  /**
   * @description 状态: 1正常 2禁用
   * @type integer | undefined, int8
   */
  status?: AdminSystemMenuPutMutationRequestStatusEnum;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  title?: string;
  /**
   * @maxLength 512
   * @type string | undefined
   */
  icon?: string;
  /**
   * @maxLength 2048
   * @type string | undefined
   */
  properties?: string;
  /**
   * @type array | undefined
   */
  resources?: Resource[];
}

export type AdminSystemMenuPutMutationResponse = AdminSystemMenuPut200;

export interface AdminSystemMenuPutMutation {
  Response: AdminSystemMenuPut200;
  Request: AdminSystemMenuPutMutationRequest;
  PathParams: AdminSystemMenuPutPathParams;
  Errors: any;
}
