/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { EmptyRes } from './EmptyRes';

export interface AdminSystemMenuDeletePathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemMenuDelete200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export type AdminSystemMenuDeleteMutationRequest = EmptyRes;

export type AdminSystemMenuDeleteMutationResponse = AdminSystemMenuDelete200;

export interface AdminSystemMenuDeleteMutation {
  Response: AdminSystemMenuDelete200;
  Request: AdminSystemMenuDeleteMutationRequest;
  PathParams: AdminSystemMenuDeletePathParams;
  Errors: any;
}
