/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';

export interface AdminSystemDepartmentPutPathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemDepartmentPut200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export interface AdminSystemDepartmentPutMutationRequest {
  /**
   * @minLength 0
   * @type integer | undefined, int32
   */
  sort?: number;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  department_name?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  remark?: string;
  /**
   * @minLength 20
   * @maxLength 20
   * @type string | undefined
   */
  parent_id?: string;
}

export type AdminSystemDepartmentPutMutationResponse = AdminSystemDepartmentPut200;

export interface AdminSystemDepartmentPutMutation {
  Response: AdminSystemDepartmentPut200;
  Request: AdminSystemDepartmentPutMutationRequest;
  PathParams: AdminSystemDepartmentPutPathParams;
  Errors: any;
}
