/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { EmptyRes } from './EmptyRes';

export interface AdminSystemRoleDeletePathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemRoleDelete200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export type AdminSystemRoleDeleteMutationRequest = EmptyRes;

export type AdminSystemRoleDeleteMutationResponse = AdminSystemRoleDelete200;

export interface AdminSystemRoleDeleteMutation {
  Response: AdminSystemRoleDelete200;
  Request: AdminSystemRoleDeleteMutationRequest;
  PathParams: AdminSystemRoleDeletePathParams;
  Errors: any;
}
