/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonPageRes } from './CommonPageRes';
import type { CommonRes } from './CommonRes';
import type { DepartmentRes } from './DepartmentRes';

export interface AdminSystemDepartmentsQueryQueryParams {
  /**
   * @minLength 0
   * @type integer | undefined, int64
   */
  page_no?: number;
  /**
   * @minLength 0
   * @type integer | undefined, int64
   */
  page_size?: number;
}

/**
 * @description success
 */
export type AdminSystemDepartmentsQuery200 = CommonRes & {
  data: CommonPageRes & {
    /**
     * @type array
     */
    list: DepartmentRes[];
  };
};

export type AdminSystemDepartmentsQueryQueryResponse = AdminSystemDepartmentsQuery200;

export interface AdminSystemDepartmentsQueryQuery {
  Response: AdminSystemDepartmentsQuery200;
  QueryParams: AdminSystemDepartmentsQueryQueryParams;
  Errors: any;
}
