/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { MenuRes } from './MenuRes';

export interface AdminSystemMenuGetPathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description success
 */
export type AdminSystemMenuGet200 = CommonRes & {
  /**
   * @type object
   */
  data: MenuRes;
};

export type AdminSystemMenuGetQueryResponse = AdminSystemMenuGet200;

export interface AdminSystemMenuGetQuery {
  Response: AdminSystemMenuGet200;
  PathParams: AdminSystemMenuGetPathParams;
  Errors: any;
}
