/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { EmptyRes } from './EmptyRes';

export interface AdminSystemDepartmentDeletePathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemDepartmentDelete200 = CommonRes & {
  /**
   * @type string
   */
  data: string;
};

export type AdminSystemDepartmentDeleteMutationRequest = EmptyRes;

export type AdminSystemDepartmentDeleteMutationResponse = AdminSystemDepartmentDelete200;

export interface AdminSystemDepartmentDeleteMutation {
  Response: AdminSystemDepartmentDelete200;
  Request: AdminSystemDepartmentDeleteMutationRequest;
  PathParams: AdminSystemDepartmentDeletePathParams;
  Errors: any;
}
