/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';

/**
 * @description 非查询返回
 */
export type AdminSystemDepartmentPost200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export interface AdminSystemDepartmentPostMutationRequest {
  /**
   * @minLength 0
   * @type integer | undefined, int32
   */
  sort?: number;
  /**
   * @maxLength 255
   * @type string
   */
  department_name: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  remark?: string;
  /**
   * @minLength 20
   * @maxLength 20
   * @type string | undefined
   */
  parent_id?: string;
}

export type AdminSystemDepartmentPostMutationResponse = AdminSystemDepartmentPost200;

export interface AdminSystemDepartmentPostMutation {
  Response: AdminSystemDepartmentPost200;
  Request: AdminSystemDepartmentPostMutationRequest;
  Errors: any;
}
