/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { IdsReq } from './IdsReq';

/**
 * @description 非查询返回
 */
export type AdminSystemPositionsDelete200 = CommonRes & {
  /**
   * @type string
   */
  data: string;
};

export type AdminSystemPositionsDeleteMutationRequest = IdsReq;

export type AdminSystemPositionsDeleteMutationResponse = AdminSystemPositionsDelete200;

export interface AdminSystemPositionsDeleteMutation {
  Response: AdminSystemPositionsDelete200;
  Request: AdminSystemPositionsDeleteMutationRequest;
  Errors: any;
}
