/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { UserRes } from './UserRes';

export interface AdminSystemUserGetPathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description success
 */
export type AdminSystemUserGet200 = CommonRes & {
  /**
   * @type object
   */
  result: UserRes;
};

export type AdminSystemUserGetQueryResponse = AdminSystemUserGet200;

export interface AdminSystemUserGetQuery {
  Response: AdminSystemUserGet200;
  PathParams: AdminSystemUserGetPathParams;
  Errors: any;
}
