/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { IdsReq } from './IdsReq';

/**
 * @description 非查询返回
 */
export type AdminSystemMenusDelete200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export type AdminSystemMenusDeleteMutationRequest = IdsReq;

export type AdminSystemMenusDeleteMutationResponse = AdminSystemMenusDelete200;

export interface AdminSystemMenusDeleteMutation {
  Response: AdminSystemMenusDelete200;
  Request: AdminSystemMenusDeleteMutationRequest;
  Errors: any;
}
