/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';

/**
 * @description 非查询返回
 */
export type AdminSystemUserPost200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export interface AdminSystemUserPostMutationRequest {
  /**
   * @minLength 6
   * @type string, password
   */
  password: string;
  /**
   * @minLength 6
   * @type string, password
   */
  confirm: string;
  /**
   * @maxLength 255
   * @type string, email
   */
  email: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  name?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  nickname?: string;
  /**
   * @type string | undefined
   */
  phone?: string;
  /**
   * @maxLength 1024
   * @type string | undefined
   */
  avatar?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  remark?: string;
  /**
   * @minLength 20
   * @maxLength 20
   * @type string | undefined
   */
  department_id?: string;
  /**
   * @type array | undefined
   */
  position_ids?: string[];
  /**
   * @type array | undefined
   */
  role_ids?: string[];
}

export type AdminSystemUserPostMutationResponse = AdminSystemUserPost200;

export interface AdminSystemUserPostMutation {
  Response: AdminSystemUserPost200;
  Request: AdminSystemUserPostMutationRequest;
  Errors: any;
}
