/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { PositionRes } from './PositionRes';

export interface AdminSystemPositionGetPathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description success
 */
export type AdminSystemPositionGet200 = CommonRes & {
  /**
   * @type object
   */
  data: PositionRes;
};

export type AdminSystemPositionGetQueryResponse = AdminSystemPositionGet200;

export interface AdminSystemPositionGetQuery {
  Response: AdminSystemPositionGet200;
  PathParams: AdminSystemPositionGetPathParams;
  Errors: any;
}
