/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { EmptyRes } from './EmptyRes';

export interface AdminSystemUserDeletePathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemUserDelete200 = CommonRes & {
  /**
   * @type string
   */
  data: string;
};

export type AdminSystemUserDeleteMutationRequest = EmptyRes;

export type AdminSystemUserDeleteMutationResponse = AdminSystemUserDelete200;

export interface AdminSystemUserDeleteMutation {
  Response: AdminSystemUserDelete200;
  Request: AdminSystemUserDeleteMutationRequest;
  PathParams: AdminSystemUserDeletePathParams;
  Errors: any;
}
