/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonPageRes } from './CommonPageRes';
import type { CommonRes } from './CommonRes';
import type { RoleRes } from './RoleRes';

export interface AdminSystemRolesQueryQueryParams {
  /**
   * @minLength 0
   * @type integer | undefined, int64
   */
  page_no?: number;
  /**
   * @minLength 0
   * @type integer | undefined, int64
   */
  page_size?: number;
  /**
   * @type array | undefined
   */
  created_at?: number[];
  /**
   * @type array | undefined
   */
  updated_at?: number[];
  /**
   * @type string | undefined
   */
  role_name?: string;
  /**
   * @type string | undefined
   */
  code?: string;
}

/**
 * @description success
 */
export type AdminSystemRolesQuery200 = CommonRes & {
  data: CommonPageRes & {
    /**
     * @type array
     */
    list: RoleRes[];
  };
};

export type AdminSystemRolesQueryQueryResponse = AdminSystemRolesQuery200;

export interface AdminSystemRolesQueryQuery {
  Response: AdminSystemRolesQuery200;
  QueryParams: AdminSystemRolesQueryQueryParams;
  Errors: any;
}
