/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { MenuRes } from './MenuRes';

/**
 * @description success
 */
export type AdminSystemMenusQuery200 = CommonRes & {
  /**
   * @type object
   */
  data: {
    /**
     * @type array | undefined
     */
    list?: MenuRes[];
  };
};

export type AdminSystemMenusQueryQueryResponse = AdminSystemMenusQuery200;

export interface AdminSystemMenusQueryQuery {
  Response: AdminSystemMenusQuery200;
  Errors: any;
}
