/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { DepartmentRes } from './DepartmentRes';

export interface AdminSystemDepartmentGetPathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description success
 */
export type AdminSystemDepartmentGet200 = CommonRes & {
  /**
   * @type object
   */
  result: DepartmentRes;
};

export type AdminSystemDepartmentGetQueryResponse = AdminSystemDepartmentGet200;

export interface AdminSystemDepartmentGetQuery {
  Response: AdminSystemDepartmentGet200;
  PathParams: AdminSystemDepartmentGetPathParams;
  Errors: any;
}
