/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';

export interface AdminSystemRolePutPathParams {
  /**
   * @minLength 20
   * @maxLength 20
   * @type string
   */
  id: string;
}

/**
 * @description 非查询返回
 */
export type AdminSystemRolePut200 = CommonRes & {
  /**
   * @type string
   */
  data: string;
};

export interface AdminSystemRolePutMutationRequest {
  /**
   * @minLength 0
   * @type integer | undefined, int32
   */
  sort?: number;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  role_name?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  code?: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  remark?: string;
  /**
   * @type array | undefined
   */
  menu_ids?: string[];
}

export type AdminSystemRolePutMutationResponse = AdminSystemRolePut200;

export interface AdminSystemRolePutMutation {
  Response: AdminSystemRolePut200;
  Request: AdminSystemRolePutMutationRequest;
  PathParams: AdminSystemRolePutPathParams;
  Errors: any;
}
