/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { IdsReq } from './IdsReq';

/**
 * @description 非查询返回
 */
export type AdminSystemRolesDelete200 = CommonRes & {
  /**
   * @type string
   */
  data: string;
};

export type AdminSystemRolesDeleteMutationRequest = IdsReq;

export type AdminSystemRolesDeleteMutationResponse = AdminSystemRolesDelete200;

export interface AdminSystemRolesDeleteMutation {
  Response: AdminSystemRolesDelete200;
  Request: AdminSystemRolesDeleteMutationRequest;
  Errors: any;
}
