/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';

/**
 * @description 非查询返回
 */
export type AdminSystemPositionPost200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export interface AdminSystemPositionPostMutationRequest {
  /**
   * @minLength 0
   * @type integer | undefined, int32
   */
  sort?: number;
  /**
   * @maxLength 255
   * @type string
   */
  position_name: string;
  /**
   * @maxLength 255
   * @type string
   */
  code: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  remark?: string;
}

export type AdminSystemPositionPostMutationResponse = AdminSystemPositionPost200;

export interface AdminSystemPositionPostMutation {
  Response: AdminSystemPositionPost200;
  Request: AdminSystemPositionPostMutationRequest;
  Errors: any;
}
