/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';

/**
 * @description 非查询返回
 */
export type AdminSystemRolePost200 = CommonRes & {
  /**
   * @type string
   */
  result: string;
};

export interface AdminSystemRolePostMutationRequest {
  /**
   * @minLength 0
   * @type integer | undefined, int32
   */
  sort?: number;
  /**
   * @maxLength 255
   * @type string
   */
  role_name: string;
  /**
   * @maxLength 255
   * @type string
   */
  code: string;
  /**
   * @maxLength 255
   * @type string | undefined
   */
  remark?: string;
  /**
   * @type array | undefined
   */
  menu_ids?: string[];
}

export type AdminSystemRolePostMutationResponse = AdminSystemRolePost200;

export interface AdminSystemRolePostMutation {
  Response: AdminSystemRolePost200;
  Request: AdminSystemRolePostMutationRequest;
  Errors: any;
}
