/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { UserRes } from './UserRes';

export interface AdminSystemUserGetByEmailQueryParams {
  /**
   * @type string, email
   */
  email: string;
}

/**
 * @description success
 */
export type AdminSystemUserGetByEmail200 = CommonRes & {
  /**
   * @type object
   */
  data: UserRes;
};

export type AdminSystemUserGetByEmailQueryResponse = AdminSystemUserGetByEmail200;

export interface AdminSystemUserGetByEmailQuery {
  Response: AdminSystemUserGetByEmail200;
  QueryParams: AdminSystemUserGetByEmailQueryParams;
  Errors: any;
}
