/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonPageRes } from './CommonPageRes';
import type { CommonRes } from './CommonRes';
import type { UserRes } from './UserRes';

export const adminSystemUsersQueryQueryParamsStatusEnum = {
  1: 1,
  2: 2,
} as const;

export type AdminSystemUsersQueryQueryParamsStatusEnum
  = (typeof adminSystemUsersQueryQueryParamsStatusEnum)[keyof typeof adminSystemUsersQueryQueryParamsStatusEnum];

export interface AdminSystemUsersQueryQueryParams {
  /**
   * @minLength 0
   * @type integer | undefined, int64
   */
  page_no?: number;
  /**
   * @minLength 0
   * @type integer | undefined, int64
   */
  page_size?: number;
  /**
   * @type array | undefined
   */
  created_at?: number[];
  /**
   * @type array | undefined
   */
  updated_at?: number[];
  /**
   * @type integer | undefined, int8
   */
  status?: AdminSystemUsersQueryQueryParamsStatusEnum;
  /**
   * @type string | undefined
   */
  email?: string;
  /**
   * @type string | undefined
   */
  name?: string;
  /**
   * @type string | undefined
   */
  nickname?: string;
  /**
   * @type string | undefined
   */
  phone?: string;
  /**
   * @type array | undefined
   */
  department_ids?: string[];
  /**
   * @type array | undefined
   */
  position_ids?: string[];
  /**
   * @type array | undefined
   */
  role_ids?: string[];
}

/**
 * @description success
 */
export type AdminSystemUsersQuery200 = CommonRes & {
  data: CommonPageRes & {
    /**
     * @type array
     */
    list: UserRes[];
  };
};

export type AdminSystemUsersQueryQueryResponse = AdminSystemUsersQuery200;

export interface AdminSystemUsersQueryQuery {
  Response: AdminSystemUsersQuery200;
  QueryParams: AdminSystemUsersQueryQueryParams;
  Errors: any;
}
