/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';
import type { EmptyRes } from './EmptyRes';

/**
 * @description success
 */
export type BaseInit200 = CommonRes;

export type BaseInitMutationRequest = EmptyRes;

export type BaseInitMutationResponse = BaseInit200;

export interface BaseInitMutation {
  Response: BaseInit200;
  Request: BaseInitMutationRequest;
  Errors: any;
}
