/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface CommonPageRes {
  /**
   * @description 页码
   * @type integer, int64
   */
  page_no: number;
  /**
   * @description 每页条目
   * @type integer, int64
   */
  page_size: number;
  /**
   * @description 总条目
   * @type integer, int64
   */
  total: number;
  /**
   * @description 是否还有更多
   * @type boolean
   */
  more: boolean;
}
