/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommonRes } from './CommonRes';

export type CommonSuccess = CommonRes & {
  /**
   * @type string
   */
  result: string;
};
