/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface CommonRes {
  /**
   * @description 响应时间戳
   * @type string
   */
  t: string;
  /**
   * @description 业务是否成功
   * @type boolean
   */
  success: boolean;
  /**
   * @description 业务code
   * @type string
   */
  code: string;
  /**
   * @description 响应信息
   * @maxLength 200
   * @type string
   */
  msg: string;
}
