/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface DepartmentRes {
  /**
   * @type string
   */
  id: string;
  /**
   * @type integer, int64
   */
  created_at: number;
  /**
   * @type integer, int64
   */
  updated_at: number;
  /**
   * @type integer, int32
   */
  sort: number;
  /**
   * @type string
   */
  department_name: string;
  /**
   * @type string
   */
  remark: string;
  /**
   * @type string
   */
  parent_id: string;
  /**
   * @type string
   */
  path: string;
  /**
   * @type integer, int32
   */
  level: number;
  /**
   * @type array
   */
  children: DepartmentRes[];
}
