/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface JwtResponse {
  /**
   * @description 访问令牌
   * @type string
   */
  access_token: string;
  /**
   * @description 访问令牌过期时间戳
   * @minLength 0
   * @type number
   */
  access_expire: number;
  /**
   * @description 刷新令牌
   * @type string
   */
  refresh_token: string;
  /**
   * @description 刷新令牌过期时间戳
   * @minLength 0
   * @type number
   */
  refresh_expire: number;
}
