/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Resource } from './Resource';

export interface MenuRes {
  /**
   * @type string
   */
  id: string;
  /**
   * @type integer, int64
   */
  created_at: number;
  /**
   * @type integer, int64
   */
  updated_at: number;
  /**
   * @type integer, int32
   */
  sort: number;
  /**
   * @type integer, int8
   */
  status: number;
  /**
   * @type string
   */
  title: string;
  /**
   * @type string
   */
  icon: string;
  /**
   * @type string
   */
  code: string;
  /**
   * @type string
   */
  code_path: string;
  /**
   * @type string
   */
  parent_id: string;
  /**
   * @type string
   */
  menu_type: string;
  /**
   * @type string
   */
  menu_path: string;
  /**
   * @type integer, int32
   */
  level: number;
  /**
   * @type string
   */
  properties: string;
  /**
   * @type array
   */
  resources: Resource[];
  /**
   * @type array
   */
  children: MenuRes[];
}
