/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface MenusRes {
  /**
   * @type string
   */
  code_path: string;
  /**
   * @type string
   */
  icon: string;
  /**
   * @type string
   */
  menu_type: string;
  /**
   * @type array
   */
  children: MenusRes[];
}
