/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface PositionRes {
  /**
   * @type string
   */
  id: string;
  /**
   * @type integer, int64
   */
  created_at: number;
  /**
   * @type integer, int64
   */
  updated_at: number;
  /**
   * @type integer, int32
   */
  sort: number;
  /**
   * @type string
   */
  position_name: string;
  /**
   * @type string
   */
  code: string;
  /**
   * @type string
   */
  remark: string;
}
