/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface Resource {
  /**
   * @maxLength 32
   * @type string
   */
  method: string;
  /**
   * @maxLength 512
   * @type string
   */
  path: string;
}
