/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DepartmentRes } from './DepartmentRes';
import type { PositionRes } from './PositionRes';
import type { RoleRes } from './RoleRes';

export interface UserRes {
  /**
   * @type string
   */
  id: string;
  /**
   * @type integer, int64
   */
  created_at: number;
  /**
   * @type integer, int64
   */
  updated_at: number;
  /**
   * @type integer, int8
   */
  status: number;
  /**
   * @type string
   */
  email: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  nickname: string;
  /**
   * @type string
   */
  phone: string;
  /**
   * @type string
   */
  avatar: string;
  /**
   * @type string
   */
  remark: string;
  /**
   * @type object
   */
  department: DepartmentRes;
  /**
   * @type array
   */
  positions: PositionRes[];
  /**
   * @type array
   */
  roles: RoleRes[];
}
