/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemPositionsQueryQueryResponse } from '../../models/AdminSystemPositionsQuery';

import { createAdminSystemPositionsQueryQueryResponseFaker } from '../../mocks/positionController/createAdminSystemPositionsQueryFaker';

export function adminSystemPositionsQueryHandler(
  data?: AdminSystemPositionsQueryQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response),
) {
  return http.get('/api/v1/admin_system/position', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemPositionsQueryQueryResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
