/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemPositionPostMutationResponse } from '../../models/AdminSystemPositionPost';

import { createAdminSystemPositionPostMutationResponseFaker } from '../../mocks/positionController/createAdminSystemPositionPostFaker';

export function adminSystemPositionPostHandler(
  data?: AdminSystemPositionPostMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
  return http.post('/api/v1/admin_system/position', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemPositionPostMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
