/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemPositionDeleteMutationResponse } from '../../models/AdminSystemPositionDelete';

import { createAdminSystemPositionDeleteMutationResponseFaker } from '../../mocks/positionController/createAdminSystemPositionDeleteFaker';

export function adminSystemPositionDeleteHandler(
  data?: AdminSystemPositionDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response),
) {
  return http.delete('/api/v1/admin_system/position/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemPositionDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
