/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemPositionsDeleteMutationResponse } from '../../models/AdminSystemPositionsDelete';

import { createAdminSystemPositionsDeleteMutationResponseFaker } from '../../mocks/positionController/createAdminSystemPositionsDeleteFaker';

export function adminSystemPositionsDeleteHandler(
  data?: AdminSystemPositionsDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
  return http.post('/api/v1/admin_system/position/delete', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemPositionsDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
