/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemPositionGetQueryResponse } from '../../models/AdminSystemPositionGet';

import { createAdminSystemPositionGetQueryResponseFaker } from '../../mocks/positionController/createAdminSystemPositionGetFaker';

export function adminSystemPositionGetHandler(
  data?: AdminSystemPositionGetQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response),
) {
  return http.get('/api/v1/admin_system/position/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemPositionGetQueryResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
