/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemPositionPutMutationResponse } from '../../models/AdminSystemPositionPut';

import { createAdminSystemPositionPutMutationResponseFaker } from '../../mocks/positionController/createAdminSystemPositionPutFaker';

export function adminSystemPositionPutHandler(
  data?: AdminSystemPositionPutMutationResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Response),
) {
  return http.put('/api/v1/admin_system/position/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemPositionPutMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
