/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemRolePutMutationResponse } from '../../models/AdminSystemRolePut';

import { createAdminSystemRolePutMutationResponseFaker } from '../../mocks/roleController/createAdminSystemRolePutFaker';

export function adminSystemRolePutHandler(data?: AdminSystemRolePutMutationResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Response)) {
  return http.put('/api/v1/admin_system/role/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemRolePutMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
