/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemRolesQueryQueryResponse } from '../../models/AdminSystemRolesQuery';

import { createAdminSystemRolesQueryQueryResponseFaker } from '../../mocks/roleController/createAdminSystemRolesQueryFaker';

export function adminSystemRolesQueryHandler(data?: AdminSystemRolesQueryQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response)) {
  return http.get('/api/v1/admin_system/role', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemRolesQueryQueryResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
