/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemRoleGetQueryResponse } from '../../models/AdminSystemRoleGet';

import { createAdminSystemRoleGetQueryResponseFaker } from '../../mocks/roleController/createAdminSystemRoleGetFaker';

export function adminSystemRoleGetHandler(data?: AdminSystemRoleGetQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response)) {
  return http.get('/api/v1/admin_system/role/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemRoleGetQueryResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
