/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemRoleDeleteMutationResponse } from '../../models/AdminSystemRoleDelete';

import { createAdminSystemRoleDeleteMutationResponseFaker } from '../../mocks/roleController/createAdminSystemRoleDeleteFaker';

export function adminSystemRoleDeleteHandler(
  data?: AdminSystemRoleDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response),
) {
  return http.delete('/api/v1/admin_system/role/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemRoleDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
