/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemRolesDeleteMutationResponse } from '../../models/AdminSystemRolesDelete';

import { createAdminSystemRolesDeleteMutationResponseFaker } from '../../mocks/roleController/createAdminSystemRolesDeleteFaker';

export function adminSystemRolesDeleteHandler(
  data?: AdminSystemRolesDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
  return http.post('/api/v1/admin_system/role/delete', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemRolesDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
