/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemRolePostMutationResponse } from '../../models/AdminSystemRolePost';

import { createAdminSystemRolePostMutationResponseFaker } from '../../mocks/roleController/createAdminSystemRolePostFaker';

export function adminSystemRolePostHandler(data?: AdminSystemRolePostMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response)) {
  return http.post('/api/v1/admin_system/role', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemRolePostMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
