/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type {
  AdminSystemMenuDeleteMutationRequest,
  AdminSystemMenuDeleteMutationResponse,
  AdminSystemMenuDeletePathParams,
} from '../../models/AdminSystemMenuDelete';

import { adminSystemMenuDeleteMutationRequestSchema, adminSystemMenuDeleteMutationResponseSchema } from '../../zod/menuController/adminSystemMenuDeleteSchema';

export function getAdminSystemMenuDeleteUrl({ id }: { id: AdminSystemMenuDeletePathParams['id'] }) {
  return `/api/v1/admin_system/menu/${id}` as const;
}

/**
 * @summary 删除单个菜单
 * {@link /api/v1/admin_system/menu/:id}
 */
export async function adminSystemMenuDelete(
  { id, data }: { id: AdminSystemMenuDeletePathParams['id']; data?: AdminSystemMenuDeleteMutationRequest },
  config: Partial<RequestConfig<AdminSystemMenuDeleteMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemMenuDeleteMutationRequestSchema.parse(data);
  const res = await request<AdminSystemMenuDeleteMutationResponse, ResponseErrorConfig<Error>, AdminSystemMenuDeleteMutationRequest>({
    method: 'DELETE',
    url: getAdminSystemMenuDeleteUrl({ id }).toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemMenuDeleteMutationResponseSchema.parse(res.data) };
}
