/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type { AdminSystemMenuGetPathParams, AdminSystemMenuGetQueryResponse } from '../../models/AdminSystemMenuGet';

import { adminSystemMenuGetQueryResponseSchema } from '../../zod/menuController/adminSystemMenuGetSchema';

export function getAdminSystemMenuGetUrl({ id }: { id: AdminSystemMenuGetPathParams['id'] }) {
  return `/api/v1/admin_system/menu/${id}` as const;
}

/**
 * @summary 查询菜单
 * {@link /api/v1/admin_system/menu/:id}
 */
export async function adminSystemMenuGet({ id }: { id: AdminSystemMenuGetPathParams['id'] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemMenuGetQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemMenuGetUrl({ id }).toString(),
    ...requestConfig,
  });
  return { ...res, data: adminSystemMenuGetQueryResponseSchema.parse(res.data) };
}
