/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type { AdminSystemMenuPutMutationRequest, AdminSystemMenuPutMutationResponse, AdminSystemMenuPutPathParams } from '../../models/AdminSystemMenuPut';

import { adminSystemMenuPutMutationRequestSchema, adminSystemMenuPutMutationResponseSchema } from '../../zod/menuController/adminSystemMenuPutSchema';

export function getAdminSystemMenuPutUrl({ id }: { id: AdminSystemMenuPutPathParams['id'] }) {
  return `/api/v1/admin_system/manu/${id}` as const;
}

/**
 * @summary 修改菜单
 * {@link /api/v1/admin_system/manu/:id}
 */
export async function adminSystemMenuPut(
  { id, data }: { id: AdminSystemMenuPutPathParams['id']; data?: AdminSystemMenuPutMutationRequest },
  config: Partial<RequestConfig<AdminSystemMenuPutMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemMenuPutMutationRequestSchema.parse(data);
  const res = await request<AdminSystemMenuPutMutationResponse, ResponseErrorConfig<Error>, AdminSystemMenuPutMutationRequest>({
    method: 'PUT',
    url: getAdminSystemMenuPutUrl({ id }).toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemMenuPutMutationResponseSchema.parse(res.data) };
}
