/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemMenusQueryQueryResponse } from '../../models/AdminSystemMenusQuery';

import { adminSystemMenusQueryQueryResponseSchema } from '../../zod/menuController/adminSystemMenusQuerySchema';

export function getAdminSystemMenusQueryUrl() {
  return `/api/v1/admin_system/menu` as const;
}

/**
 * @summary 查询多个菜单
 * {@link /api/v1/admin_system/menu}
 */
export async function adminSystemMenusQuery(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemMenusQueryQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemMenusQueryUrl().toString(),
    ...requestConfig,
  });
  return { ...res, data: adminSystemMenusQueryQueryResponseSchema.parse(res.data) };
}
