/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type { AdminSystemMenuPostMutationRequest, AdminSystemMenuPostMutationResponse } from '../../models/AdminSystemMenuPost';

import { adminSystemMenuPostMutationRequestSchema, adminSystemMenuPostMutationResponseSchema } from '../../zod/menuController/adminSystemMenuPostSchema';

export function getAdminSystemMenuPostUrl() {
  return `/api/v1/admin_system/menu` as const;
}

/**
 * @summary 新增菜单
 * {@link /api/v1/admin_system/menu}
 */
export async function adminSystemMenuPost(
  { data }: { data: AdminSystemMenuPostMutationRequest },
  config: Partial<RequestConfig<AdminSystemMenuPostMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemMenuPostMutationRequestSchema.parse(data);
  const res = await request<AdminSystemMenuPostMutationResponse, ResponseErrorConfig<Error>, AdminSystemMenuPostMutationRequest>({
    method: 'POST',
    url: getAdminSystemMenuPostUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemMenuPostMutationResponseSchema.parse(res.data) };
}
