/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemMenusDeleteMutationRequest, AdminSystemMenusDeleteMutationResponse } from '../../models/AdminSystemMenusDelete';

import {
  adminSystemMenusDeleteMutationRequestSchema,
  adminSystemMenusDeleteMutationResponseSchema,
} from '../../zod/menuController/adminSystemMenusDeleteSchema';

export function getAdminSystemMenusDeleteUrl() {
  return `/api/v1/admin_system/menu/delete` as const;
}

/**
 * @summary 删除多个菜单
 * {@link /api/v1/admin_system/menu/delete}
 */
export async function adminSystemMenusDelete(
  { data }: { data: AdminSystemMenusDeleteMutationRequest },
  config: Partial<RequestConfig<AdminSystemMenusDeleteMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemMenusDeleteMutationRequestSchema.parse(data);
  const res = await request<AdminSystemMenusDeleteMutationResponse, ResponseErrorConfig<Error>, AdminSystemMenusDeleteMutationRequest>({
    method: 'POST',
    url: getAdminSystemMenusDeleteUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemMenusDeleteMutationResponseSchema.parse(res.data) };
}
