/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { adminSystemMenuDelete } from './adminSystemMenuDelete';
import { adminSystemMenuGet } from './adminSystemMenuGet';
import { adminSystemMenuPost } from './adminSystemMenuPost';
import { adminSystemMenuPut } from './adminSystemMenuPut';
import { adminSystemMenusDelete } from './adminSystemMenusDelete';
import { adminSystemMenusQuery } from './adminSystemMenusQuery';

export function menuService() {
  return { adminSystemMenuPost, adminSystemMenusQuery, adminSystemMenusDelete, adminSystemMenuDelete, adminSystemMenuPut, adminSystemMenuGet };
}
