/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const operations = {
  accountLoginPassword: {
    path: '/api/v1/admin_system/account/login_password',
    method: 'post',
  },
  adminSystemDepartmentPost: {
    path: '/api/v1/admin_system/department',
    method: 'post',
  },
  adminSystemDepartmentsQuery: {
    path: '/api/v1/admin_system/department',
    method: 'get',
  },
  adminSystemDepartmentsDelete: {
    path: '/api/v1/admin_system/department/delete',
    method: 'post',
  },
  adminSystemDepartmentDelete: {
    path: '/api/v1/admin_system/department/:id',
    method: 'delete',
  },
  adminSystemDepartmentPut: {
    path: '/api/v1/admin_system/department/:id',
    method: 'put',
  },
  adminSystemDepartmentGet: {
    path: '/api/v1/admin_system/department/:id',
    method: 'get',
  },
} as const;
