/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';

export const adminSystemUserPutPathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemUserPutPathParamsSchema = z.infer<typeof adminSystemUserPutPathParamsSchema>;

/**
 * @description 非查询返回
 */
export const adminSystemUserPut200Schema = commonResSchema.and(
  z.object({
    result: z.string(),
  }),
);

export type AdminSystemUserPut200Schema = z.infer<typeof adminSystemUserPut200Schema>;

export const adminSystemUserPutMutationRequestSchema = z.object({
  status: z.union([z.literal(1), z.literal(2)]).optional(),
  password: z.string().min(6).optional(),
  confirm: z.string().min(6).optional(),
  email: z.email().max(255).optional(),
  name: z.string().max(255).optional(),
  nickname: z.string().max(255).optional(),
  phone: z
    .string()
    .regex(/^\d+$/)
    .optional(),
  avatar: z.string().max(1024).optional(),
  remark: z.string().max(255).optional(),
  department_id: z.string().min(20).max(20).optional(),
  position_ids: z.array(z.string()).optional(),
  role_ids: z.array(z.string()).optional(),
});

export type AdminSystemUserPutMutationRequestSchema = z.infer<typeof adminSystemUserPutMutationRequestSchema>;

export const adminSystemUserPutMutationResponseSchema = adminSystemUserPut200Schema;

export type AdminSystemUserPutMutationResponseSchema = z.infer<typeof adminSystemUserPutMutationResponseSchema>;
