/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonPageResSchema } from '../commonPageResSchema';
import { commonResSchema } from '../commonResSchema';
import { userResSchema } from '../userResSchema';

export const adminSystemUsersQueryQueryParamsSchema = z
  .object({
    page_no: z.coerce.number().int().min(0).optional(),
    page_size: z.coerce.number().int().min(0).optional(),
    created_at: z.array(z.coerce.number().int()).max(2).optional(),
    updated_at: z.array(z.coerce.number().int()).max(2).optional(),
    status: z.union([z.literal(1), z.literal(2)]).optional(),
    email: z.string().optional(),
    name: z.string().optional(),
    nickname: z.string().optional(),
    phone: z.string().optional(),
    department_ids: z.array(z.string()).optional(),
    position_ids: z.array(z.string()).optional(),
    role_ids: z.array(z.string()).optional(),
  })
  .optional();

export type AdminSystemUsersQueryQueryParamsSchema = z.infer<typeof adminSystemUsersQueryQueryParamsSchema>;

/**
 * @description success
 */
export const adminSystemUsersQuery200Schema = commonResSchema.and(
  z.object({
    get result() {
      return commonPageResSchema.and(
        z.object({
          get list() {
            return z.array(userResSchema);
          },
        }),
      );
    },
  }),
);

export type AdminSystemUsersQuery200Schema = z.infer<typeof adminSystemUsersQuery200Schema>;

export const adminSystemUsersQueryQueryResponseSchema = adminSystemUsersQuery200Schema;

export type AdminSystemUsersQueryQueryResponseSchema = z.infer<typeof adminSystemUsersQueryQueryResponseSchema>;
