/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';

/**
 * @description 非查询返回
 */
export const adminSystemUserPost200Schema = commonResSchema.and(
  z.object({
    result: z.string(),
  }),
);

export type AdminSystemUserPost200Schema = z.infer<typeof adminSystemUserPost200Schema>;

export const adminSystemUserPostMutationRequestSchema = z.object({
  password: z.string().min(6),
  confirm: z.string().min(6),
  email: z.email().max(255),
  name: z.string().max(255).optional(),
  nickname: z.string().max(255).optional(),
  phone: z.string().optional(),
  avatar: z.string().max(1024).optional(),
  remark: z.string().max(255).optional(),
  department_id: z.string().min(20).max(20).optional(),
  position_ids: z.array(z.string()).optional(),
  role_ids: z.array(z.string()).optional(),
});

export type AdminSystemUserPostMutationRequestSchema = z.infer<typeof adminSystemUserPostMutationRequestSchema>;

export const adminSystemUserPostMutationResponseSchema = adminSystemUserPost200Schema;

export type AdminSystemUserPostMutationResponseSchema = z.infer<typeof adminSystemUserPostMutationResponseSchema>;
