/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { emptyResSchema } from '../emptyResSchema';

export const adminSystemUserDeletePathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemUserDeletePathParamsSchema = z.infer<typeof adminSystemUserDeletePathParamsSchema>;

/**
 * @description 非查询返回
 */
export const adminSystemUserDelete200Schema = commonResSchema.and(
  z.object({
    result: z.string(),
  }),
);

export type AdminSystemUserDelete200Schema = z.infer<typeof adminSystemUserDelete200Schema>;

export const adminSystemUserDeleteMutationRequestSchema = emptyResSchema;

export type AdminSystemUserDeleteMutationRequestSchema = z.infer<typeof adminSystemUserDeleteMutationRequestSchema>;

export const adminSystemUserDeleteMutationResponseSchema = adminSystemUserDelete200Schema;

export type AdminSystemUserDeleteMutationResponseSchema = z.infer<typeof adminSystemUserDeleteMutationResponseSchema>;
