/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { userResSchema } from '../userResSchema';

export const adminSystemUserGetByEmailQueryParamsSchema = z.object({
  email: z.email(),
});

export type AdminSystemUserGetByEmailQueryParamsSchema = z.infer<typeof adminSystemUserGetByEmailQueryParamsSchema>;

/**
 * @description success
 */
export const adminSystemUserGetByEmail200Schema = commonResSchema.and(
  z.object({
    get data() {
      return userResSchema;
    },
  }),
);

export type AdminSystemUserGetByEmail200Schema = z.infer<typeof adminSystemUserGetByEmail200Schema>;

export const adminSystemUserGetByEmailQueryResponseSchema = adminSystemUserGetByEmail200Schema;

export type AdminSystemUserGetByEmailQueryResponseSchema = z.infer<typeof adminSystemUserGetByEmailQueryResponseSchema>;
