/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { idsReqSchema } from '../idsReqSchema';

/**
 * @description 非查询返回
 */
export const adminSystemUsersDelete200Schema = commonResSchema.and(
  z.object({
    data: z.string(),
  }),
);

export type AdminSystemUsersDelete200Schema = z.infer<typeof adminSystemUsersDelete200Schema>;

export const adminSystemUsersDeleteMutationRequestSchema = idsReqSchema;

export type AdminSystemUsersDeleteMutationRequestSchema = z.infer<typeof adminSystemUsersDeleteMutationRequestSchema>;

export const adminSystemUsersDeleteMutationResponseSchema = adminSystemUsersDelete200Schema;

export type AdminSystemUsersDeleteMutationResponseSchema = z.infer<typeof adminSystemUsersDeleteMutationResponseSchema>;
