/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { jwtResponseSchema } from '../jwtResponseSchema';

/**
 * @description success
 */
export const accountRefresh200Schema = commonResSchema.and(
  z.object({
    get data() {
      return jwtResponseSchema;
    },
  }),
);

export type AccountRefresh200Schema = z.infer<typeof accountRefresh200Schema>;

export const accountRefreshMutationRequestSchema = z.object({
  refresh_token: z.string(),
});

export type AccountRefreshMutationRequestSchema = z.infer<typeof accountRefreshMutationRequestSchema>;

export const accountRefreshMutationResponseSchema = accountRefresh200Schema;

export type AccountRefreshMutationResponseSchema = z.infer<typeof accountRefreshMutationResponseSchema>;
