/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { emptyResSchema } from '../emptyResSchema';

/**
 * @description success
 */
export const accountLogout200Schema = commonResSchema;

export type AccountLogout200Schema = z.infer<typeof accountLogout200Schema>;

export const accountLogoutMutationRequestSchema = emptyResSchema;

export type AccountLogoutMutationRequestSchema = z.infer<typeof accountLogoutMutationRequestSchema>;

export const accountLogoutMutationResponseSchema = accountLogout200Schema;

export type AccountLogoutMutationResponseSchema = z.infer<typeof accountLogoutMutationResponseSchema>;
