/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { accountInfoResSchema } from '../accountInfoResSchema';
import { commonResSchema } from '../commonResSchema';

/**
 * @description success
 */
export const accountInfo200Schema = commonResSchema.and(
  z.object({
    get result() {
      return accountInfoResSchema;
    },
  }),
);

export type AccountInfo200Schema = z.infer<typeof accountInfo200Schema>;

export const accountInfoQueryResponseSchema = accountInfo200Schema;

export type AccountInfoQueryResponseSchema = z.infer<typeof accountInfoQueryResponseSchema>;
