/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { jwtResponseSchema } from '../jwtResponseSchema';

/**
 * @description success
 */
export const accountLoginPassword200Schema = commonResSchema.and(
  z.object({
    get data() {
      return jwtResponseSchema;
    },
  }),
);

export type AccountLoginPassword200Schema = z.infer<typeof accountLoginPassword200Schema>;

export const accountLoginPasswordMutationRequestSchema = z.object({
  email: z.email().describe('邮箱'),
  password: z.string().min(6).max(20).describe('密码'),
});

export type AccountLoginPasswordMutationRequestSchema = z.infer<typeof accountLoginPasswordMutationRequestSchema>;

export const accountLoginPasswordMutationResponseSchema = accountLoginPassword200Schema;

export type AccountLoginPasswordMutationResponseSchema = z.infer<typeof accountLoginPasswordMutationResponseSchema>;
