/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type {
  AdminSystemDepartmentDeleteMutationRequest,
  AdminSystemDepartmentDeleteMutationResponse,
  AdminSystemDepartmentDeletePathParams,
} from '../../models/AdminSystemDepartmentDelete';

import {
  adminSystemDepartmentDeleteMutationRequestSchema,
  adminSystemDepartmentDeleteMutationResponseSchema,
} from '../../zod/departmentController/adminSystemDepartmentDeleteSchema';

export function getAdminSystemDepartmentDeleteUrl({ id }: { id: AdminSystemDepartmentDeletePathParams['id'] }) {
  return `/api/v1/admin_system/department/${id}` as const;
}

/**
 * @summary 删除单个部门
 * {@link /api/v1/admin_system/department/:id}
 */
export async function adminSystemDepartmentDelete(
  { id, data }: { id: AdminSystemDepartmentDeletePathParams['id']; data?: AdminSystemDepartmentDeleteMutationRequest },
  config: Partial<RequestConfig<AdminSystemDepartmentDeleteMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemDepartmentDeleteMutationRequestSchema.parse(data);
  const res = await request<AdminSystemDepartmentDeleteMutationResponse, ResponseErrorConfig<Error>, AdminSystemDepartmentDeleteMutationRequest>({
    method: 'DELETE',
    url: getAdminSystemDepartmentDeleteUrl({ id }).toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemDepartmentDeleteMutationResponseSchema.parse(res.data) };
}
