/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type { AdminSystemDepartmentPostMutationRequest, AdminSystemDepartmentPostMutationResponse } from '../../models/AdminSystemDepartmentPost';

import {
  adminSystemDepartmentPostMutationRequestSchema,
  adminSystemDepartmentPostMutationResponseSchema,
} from '../../zod/departmentController/adminSystemDepartmentPostSchema';

export function getAdminSystemDepartmentPostUrl() {
  return `/api/v1/admin_system/department` as const;
}

/**
 * @summary 新增部门
 * {@link /api/v1/admin_system/department}
 */
export async function adminSystemDepartmentPost(
  { data }: { data: AdminSystemDepartmentPostMutationRequest },
  config: Partial<RequestConfig<AdminSystemDepartmentPostMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemDepartmentPostMutationRequestSchema.parse(data);
  const res = await request<AdminSystemDepartmentPostMutationResponse, ResponseErrorConfig<Error>, AdminSystemDepartmentPostMutationRequest>({
    method: 'POST',
    url: getAdminSystemDepartmentPostUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemDepartmentPostMutationResponseSchema.parse(res.data) };
}
