/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/utils/ky-client';

import fetch from '@/utils/ky-client';

import type { AdminSystemDepartmentGetPathParams, AdminSystemDepartmentGetQueryResponse } from '../../models/AdminSystemDepartmentGet';

import { adminSystemDepartmentGetQueryResponseSchema } from '../../zod/departmentController/adminSystemDepartmentGetSchema';

export function getAdminSystemDepartmentGetUrl({ id }: { id: AdminSystemDepartmentGetPathParams['id'] }) {
  return `/api/v1/admin_system/department/${id}` as const;
}

/**
 * @summary 查询部门
 * {@link /api/v1/admin_system/department/:id}
 */
export async function adminSystemDepartmentGet(
  { id }: { id: AdminSystemDepartmentGetPathParams['id'] },
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemDepartmentGetQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemDepartmentGetUrl({ id }).toString(),
    ...requestConfig,
  });
  return { ...res, data: adminSystemDepartmentGetQueryResponseSchema.parse(res.data) };
}
