/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type { AdminSystemDepartmentsDeleteMutationRequest, AdminSystemDepartmentsDeleteMutationResponse } from '../../models/AdminSystemDepartmentsDelete';

import {
  adminSystemDepartmentsDeleteMutationRequestSchema,
  adminSystemDepartmentsDeleteMutationResponseSchema,
} from '../../zod/departmentController/adminSystemDepartmentsDeleteSchema';

export function getAdminSystemDepartmentsDeleteUrl() {
  return `/api/v1/admin_system/department/delete` as const;
}

/**
 * @summary 删除多个部门
 * {@link /api/v1/admin_system/department/delete}
 */
export async function adminSystemDepartmentsDelete(
  { data }: { data: AdminSystemDepartmentsDeleteMutationRequest },
  config: Partial<RequestConfig<AdminSystemDepartmentsDeleteMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemDepartmentsDeleteMutationRequestSchema.parse(data);
  const res = await request<AdminSystemDepartmentsDeleteMutationResponse, ResponseErrorConfig<Error>, AdminSystemDepartmentsDeleteMutationRequest>({
    method: 'POST',
    url: getAdminSystemDepartmentsDeleteUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemDepartmentsDeleteMutationResponseSchema.parse(res.data) };
}
