/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/utils/ky-client';

import fetch from '@/utils/ky-client';

import type {
  AdminSystemDepartmentPutMutationRequest,
  AdminSystemDepartmentPutMutationResponse,
  AdminSystemDepartmentPutPathParams,
} from '../../models/AdminSystemDepartmentPut';

import {
  adminSystemDepartmentPutMutationRequestSchema,
  adminSystemDepartmentPutMutationResponseSchema,
} from '../../zod/departmentController/adminSystemDepartmentPutSchema';

export function getAdminSystemDepartmentPutUrl({ id }: { id: AdminSystemDepartmentPutPathParams['id'] }) {
  return `/api/v1/admin_system/department/${id}` as const;
}

/**
 * @summary 修改部门
 * {@link /api/v1/admin_system/department/:id}
 */
export async function adminSystemDepartmentPut(
  { id, data }: { id: AdminSystemDepartmentPutPathParams['id']; data?: AdminSystemDepartmentPutMutationRequest },
  config: Partial<RequestConfig<AdminSystemDepartmentPutMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemDepartmentPutMutationRequestSchema.parse(data);
  const res = await request<AdminSystemDepartmentPutMutationResponse, ResponseErrorConfig<Error>, AdminSystemDepartmentPutMutationRequest>({
    method: 'PUT',
    url: getAdminSystemDepartmentPutUrl({ id }).toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemDepartmentPutMutationResponseSchema.parse(res.data) };
}
