/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { adminSystemDepartmentDelete } from './adminSystemDepartmentDelete';
import { adminSystemDepartmentGet } from './adminSystemDepartmentGet';
import { adminSystemDepartmentPost } from './adminSystemDepartmentPost';
import { adminSystemDepartmentPut } from './adminSystemDepartmentPut';
import { adminSystemDepartmentsDelete } from './adminSystemDepartmentsDelete';
import { adminSystemDepartmentsQuery } from './adminSystemDepartmentsQuery';

export function departmentService() {
  return {
    adminSystemDepartmentPost,
    adminSystemDepartmentsQuery,
    adminSystemDepartmentsDelete,
    adminSystemDepartmentDelete,
    adminSystemDepartmentPut,
    adminSystemDepartmentGet,
  };
}
