/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type {
  AdminSystemDepartmentPut200,
  AdminSystemDepartmentPutMutationRequest,
  AdminSystemDepartmentPutMutationResponse,
  AdminSystemDepartmentPutPathParams,
} from '../../models/AdminSystemDepartmentPut';

import { createCommonResFaker } from '../createCommonResFaker';

export function createAdminSystemDepartmentPutPathParamsFaker(data?: Partial<AdminSystemDepartmentPutPathParams>): AdminSystemDepartmentPutPathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description 非查询返回
 */
export function createAdminSystemDepartmentPut200Faker(data?: Partial<AdminSystemDepartmentPut200>): AdminSystemDepartmentPut200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: faker.string.alpha() });
}

export function createAdminSystemDepartmentPutMutationRequestFaker(
  data?: Partial<AdminSystemDepartmentPutMutationRequest>,
): AdminSystemDepartmentPutMutationRequest {
  faker.seed([2021]);
  return {
    ...{
      sort: faker.number.int({ min: 0 }),
      department_name: faker.string.alpha({ length: 255 }),
      remark: faker.string.alpha({ length: 255 }),
      parent_id: faker.string.alpha({ length: { min: 20, max: 20 } }),
    },
    ...(data || {}),
  };
}

export function createAdminSystemDepartmentPutMutationResponseFaker(
  data?: Partial<AdminSystemDepartmentPutMutationResponse>,
): AdminSystemDepartmentPutMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemDepartmentPut200Faker()]);
}
