/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type {
  AdminSystemDepartmentsQuery200,
  AdminSystemDepartmentsQueryQueryParams,
  AdminSystemDepartmentsQueryQueryResponse,
} from '../../models/AdminSystemDepartmentsQuery';

import { createCommonPageResFaker } from '../createCommonPageResFaker';
import { createCommonResFaker } from '../createCommonResFaker';
import { createDepartmentResFaker } from '../createDepartmentResFaker';

export function createAdminSystemDepartmentsQueryQueryParamsFaker(
  data?: Partial<AdminSystemDepartmentsQueryQueryParams>,
): AdminSystemDepartmentsQueryQueryParams {
  faker.seed([2021]);
  return {
    ...{ page_no: 1, page_size: 10 },
    ...(data || {}),
  };
}

/**
 * @description success
 */
export function createAdminSystemDepartmentsQuery200Faker(data?: Partial<AdminSystemDepartmentsQuery200>): AdminSystemDepartmentsQuery200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), {
    data: Object.assign({}, createCommonPageResFaker(), { list: faker.helpers.multiple(() => createDepartmentResFaker()) }),
  });
}

export function createAdminSystemDepartmentsQueryQueryResponseFaker(
  data?: Partial<AdminSystemDepartmentsQueryQueryResponse>,
): AdminSystemDepartmentsQueryQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemDepartmentsQuery200Faker()]);
}
