/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemDepartmentsDelete200, AdminSystemDepartmentsDeleteMutationResponse } from '../../models/AdminSystemDepartmentsDelete';

import { createCommonResFaker } from '../createCommonResFaker';
import { createIdsReqFaker } from '../createIdsReqFaker';

/**
 * @description 非查询返回
 */
export function createAdminSystemDepartmentsDelete200Faker(data?: Partial<AdminSystemDepartmentsDelete200>): AdminSystemDepartmentsDelete200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: faker.string.alpha() });
}

export function createAdminSystemDepartmentsDeleteMutationRequestFaker() {
  faker.seed([2021]);
  return createIdsReqFaker();
}

export function createAdminSystemDepartmentsDeleteMutationResponseFaker(
  data?: Partial<AdminSystemDepartmentsDeleteMutationResponse>,
): AdminSystemDepartmentsDeleteMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemDepartmentsDelete200Faker()]);
}
