/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type {
  AdminSystemDepartmentGet200,
  AdminSystemDepartmentGetPathParams,
  AdminSystemDepartmentGetQueryResponse,
} from '../../models/AdminSystemDepartmentGet';

import { createCommonResFaker } from '../createCommonResFaker';
import { createDepartmentResFaker } from '../createDepartmentResFaker';

export function createAdminSystemDepartmentGetPathParamsFaker(data?: Partial<AdminSystemDepartmentGetPathParams>): AdminSystemDepartmentGetPathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description success
 */
export function createAdminSystemDepartmentGet200Faker(data?: Partial<AdminSystemDepartmentGet200>): AdminSystemDepartmentGet200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: createDepartmentResFaker() });
}

export function createAdminSystemDepartmentGetQueryResponseFaker(data?: Partial<AdminSystemDepartmentGetQueryResponse>): AdminSystemDepartmentGetQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemDepartmentGet200Faker()]);
}
