/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemRolePostMutationRequest, AdminSystemRolePostMutationResponse } from '../../models/AdminSystemRolePost';

import { adminSystemRolePostMutationRequestSchema, adminSystemRolePostMutationResponseSchema } from '../../zod/roleController/adminSystemRolePostSchema';

export function getAdminSystemRolePostUrl() {
  return `/api/v1/admin_system/role` as const;
}

/**
 * @summary 新增角色
 * {@link /api/v1/admin_system/role}
 */
export async function adminSystemRolePost(
  { data }: { data: AdminSystemRolePostMutationRequest },
  config: Partial<RequestConfig<AdminSystemRolePostMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemRolePostMutationRequestSchema.parse(data);
  const res = await request<AdminSystemRolePostMutationResponse, ResponseErrorConfig<Error>, AdminSystemRolePostMutationRequest>({
    method: 'POST',
    url: getAdminSystemRolePostUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemRolePostMutationResponseSchema.parse(res.data) };
}
