/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemRolesQueryQueryParams, AdminSystemRolesQueryQueryResponse } from '../../models/AdminSystemRolesQuery';

import { adminSystemRolesQueryQueryResponseSchema } from '../../zod/roleController/adminSystemRolesQuerySchema';

export function getAdminSystemRolesQueryUrl() {
  return `/api/v1/admin_system/role` as const;
}

/**
 * @summary 查询多个角色
 * {@link /api/v1/admin_system/role}
 */
export async function adminSystemRolesQuery(
  { params }: { params?: AdminSystemRolesQueryQueryParams },
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemRolesQueryQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemRolesQueryUrl().toString(),
    params,
    ...requestConfig,
  });
  return { ...res, data: adminSystemRolesQueryQueryResponseSchema.parse(res.data) };
}
