/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemRolePutMutationRequest, AdminSystemRolePutMutationResponse, AdminSystemRolePutPathParams } from '../../models/AdminSystemRolePut';

import { adminSystemRolePutMutationRequestSchema, adminSystemRolePutMutationResponseSchema } from '../../zod/roleController/adminSystemRolePutSchema';

export function getAdminSystemRolePutUrl({ id }: { id: AdminSystemRolePutPathParams['id'] }) {
  return `/api/v1/admin_system/role/${id}` as const;
}

/**
 * @summary 修改角色
 * {@link /api/v1/admin_system/role/:id}
 */
export async function adminSystemRolePut(
  { id, data }: { id: AdminSystemRolePutPathParams['id']; data?: AdminSystemRolePutMutationRequest },
  config: Partial<RequestConfig<AdminSystemRolePutMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemRolePutMutationRequestSchema.parse(data);
  const res = await request<AdminSystemRolePutMutationResponse, ResponseErrorConfig<Error>, AdminSystemRolePutMutationRequest>({
    method: 'PUT',
    url: getAdminSystemRolePutUrl({ id }).toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemRolePutMutationResponseSchema.parse(res.data) };
}
