/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type {
  AdminSystemRoleDeleteMutationRequest,
  AdminSystemRoleDeleteMutationResponse,
  AdminSystemRoleDeletePathParams,
} from '../../models/AdminSystemRoleDelete';

import { adminSystemRoleDeleteMutationRequestSchema, adminSystemRoleDeleteMutationResponseSchema } from '../../zod/roleController/adminSystemRoleDeleteSchema';

export function getAdminSystemRoleDeleteUrl({ id }: { id: AdminSystemRoleDeletePathParams['id'] }) {
  return `/api/v1/admin_system/role/${id}` as const;
}

/**
 * @summary 删除单个角色
 * {@link /api/v1/admin_system/role/:id}
 */
export async function adminSystemRoleDelete(
  { id, data }: { id: AdminSystemRoleDeletePathParams['id']; data?: AdminSystemRoleDeleteMutationRequest },
  config: Partial<RequestConfig<AdminSystemRoleDeleteMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemRoleDeleteMutationRequestSchema.parse(data);
  const res = await request<AdminSystemRoleDeleteMutationResponse, ResponseErrorConfig<Error>, AdminSystemRoleDeleteMutationRequest>({
    method: 'DELETE',
    url: getAdminSystemRoleDeleteUrl({ id }).toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemRoleDeleteMutationResponseSchema.parse(res.data) };
}
