/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type { AdminSystemRolesDeleteMutationRequest, AdminSystemRolesDeleteMutationResponse } from '../../models/AdminSystemRolesDelete';

import {
  adminSystemRolesDeleteMutationRequestSchema,
  adminSystemRolesDeleteMutationResponseSchema,
} from '../../zod/roleController/adminSystemRolesDeleteSchema';

export function getAdminSystemRolesDeleteUrl() {
  return `/api/v1/admin_system/role/delete` as const;
}

/**
 * @summary 删除多个角色
 * {@link /api/v1/admin_system/role/delete}
 */
export async function adminSystemRolesDelete(
  { data }: { data: AdminSystemRolesDeleteMutationRequest },
  config: Partial<RequestConfig<AdminSystemRolesDeleteMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemRolesDeleteMutationRequestSchema.parse(data);
  const res = await request<AdminSystemRolesDeleteMutationResponse, ResponseErrorConfig<Error>, AdminSystemRolesDeleteMutationRequest>({
    method: 'POST',
    url: getAdminSystemRolesDeleteUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemRolesDeleteMutationResponseSchema.parse(res.data) };
}
