/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemRoleGetPathParams, AdminSystemRoleGetQueryResponse } from '../../models/AdminSystemRoleGet';

import { adminSystemRoleGetQueryResponseSchema } from '../../zod/roleController/adminSystemRoleGetSchema';

export function getAdminSystemRoleGetUrl({ id }: { id: AdminSystemRoleGetPathParams['id'] }) {
  return `/api/v1/admin_system/role/${id}` as const;
}

/**
 * @summary 查询角色
 * {@link /api/v1/admin_system/role/:id}
 */
export async function adminSystemRoleGet({ id }: { id: AdminSystemRoleGetPathParams['id'] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemRoleGetQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemRoleGetUrl({ id }).toString(),
    ...requestConfig,
  });
  return { ...res, data: adminSystemRoleGetQueryResponseSchema.parse(res.data) };
}
