/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { adminSystemRoleDelete } from './adminSystemRoleDelete';
import { adminSystemRoleGet } from './adminSystemRoleGet';
import { adminSystemRolePost } from './adminSystemRolePost';
import { adminSystemRolePut } from './adminSystemRolePut';
import { adminSystemRolesDelete } from './adminSystemRolesDelete';
import { adminSystemRolesQuery } from './adminSystemRolesQuery';

export function roleService() {
  return { adminSystemRolePost, adminSystemRolesQuery, adminSystemRolesDelete, adminSystemRoleDelete, adminSystemRolePut, adminSystemRoleGet };
}
