/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { BaseInitMutationResponse } from '../../models/BaseInit';

import { createCommonResFaker } from '../createCommonResFaker';
import { createEmptyResFaker } from '../createEmptyResFaker';

/**
 * @description success
 */
export function createBaseInit200Faker() {
  faker.seed([2021]);
  return createCommonResFaker();
}

export function createBaseInitMutationRequestFaker() {
  faker.seed([2021]);
  return createEmptyResFaker();
}

export function createBaseInitMutationResponseFaker(data?: Partial<BaseInitMutationResponse>): BaseInitMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createBaseInit200Faker()]);
}
