/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const commonResSchema = z.object({
  t: z.string().describe('响应时间戳'),
  success: z.boolean().describe('业务是否成功'),
  code: z.string().describe('业务code'),
  msg: z.string().max(200).describe('响应信息'),
});

export type CommonResSchema = z.infer<typeof commonResSchema>;
