/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const commonPageResSchema = z.object({
  page_no: z.int().describe('页码'),
  page_size: z.int().describe('每页条目'),
  total: z.int().describe('总条目'),
  more: z.boolean().describe('是否还有更多'),
});

export type CommonPageResSchema = z.infer<typeof commonPageResSchema>;
