/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from './commonResSchema';

export const commonSuccessSchema = commonResSchema.and(
  z.object({
    data: z.string(),
  }),
);

export type CommonSuccessSchema = z.infer<typeof commonSuccessSchema>;
