/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const commonResSchema = z.object({
  t: z.string().describe('响应时间戳'),
  success: z.boolean().describe('业务是否成功'),
  code: z
    .enum(['000000', '000001', '000002', '100000', '200000', '400001', '400002', '400003', '400004', '500001', '500002'])
    .describe('业务代码，会用于提示多语言'),
  msg: z.string().max(200).describe('响应信息'),
});

export type CommonResSchema = z.infer<typeof commonResSchema>;
