/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const departmentResSchema = z.object({
  id: z.string(),
  created_at: z.int(),
  updated_at: z.int(),
  sort: z.int(),
  department_name: z.string(),
  remark: z.string(),
  parent_id: z.string(),
  path: z.string(),
  level: z.int(),
  get children() {
    return z.array(departmentResSchema);
  },
});

export type DepartmentResSchema = z.infer<typeof departmentResSchema>;
