/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const emptyResSchema = z.object({});

export type EmptyResSchema = z.infer<typeof emptyResSchema>;
