/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const idsReqSchema = z.object({
  ids: z.array(z.string().min(20).max(20)).min(1),
});

export type IdsReqSchema = z.infer<typeof idsReqSchema>;
