/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const menusResSchema = z.object({
  code_path: z.string(),
  icon: z.string(),
  menu_type: z.string(),
  get children() {
    return z.array(menusResSchema);
  },
});

export type MenusResSchema = z.infer<typeof menusResSchema>;
