/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { resourceSchema } from './resourceSchema';

export const menuResSchema = z.object({
  id: z.string(),
  created_at: z.int(),
  updated_at: z.int(),
  sort: z.int(),
  status: z.int(),
  title: z.string(),
  icon: z.string(),
  code: z.string(),
  code_path: z.string(),
  parent_id: z.string(),
  menu_type: z.string(),
  menu_path: z.string(),
  level: z.int(),
  properties: z.string(),
  get resources() {
    return z.array(resourceSchema);
  },
  get children() {
    return z.array(menuResSchema);
  },
});

export type MenuResSchema = z.infer<typeof menuResSchema>;
