/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const positionResSchema = z.object({
  id: z.string(),
  created_at: z.int(),
  updated_at: z.int(),
  sort: z.int(),
  position_name: z.string(),
  code: z.string(),
  remark: z.string(),
});

export type PositionResSchema = z.infer<typeof positionResSchema>;
