/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const resourceSchema = z.object({
  method: z.string().max(32),
  path: z.string().max(512),
});

export type ResourceSchema = z.infer<typeof resourceSchema>;
