/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const roleResSchema = z.object({
  id: z.string(),
  created_at: z.int(),
  updated_at: z.int(),
  sort: z.int(),
  role_name: z.string(),
  code: z.string(),
  remark: z.string(),
  menu_ids: z.array(z.string()),
});

export type RoleResSchema = z.infer<typeof roleResSchema>;
