/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { z } from 'zod/v4';

import { commonResSchema } from './commonResSchema';

export const unknownErrorSchema = commonResSchema;

export type UnknownErrorSchema = z.infer<typeof unknownErrorSchema>;
