/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { departmentResSchema } from './departmentResSchema';
import { positionResSchema } from './positionResSchema';
import { roleResSchema } from './roleResSchema';

export const userResSchema = z.object({
  id: z.string(),
  created_at: z.int(),
  updated_at: z.int(),
  status: z.int(),
  email: z.string(),
  name: z.string(),
  nickname: z.string(),
  phone: z.string(),
  avatar: z.string(),
  remark: z.string(),
  get department() {
    return departmentResSchema;
  },
  get positions() {
    return z.array(positionResSchema);
  },
  get roles() {
    return z.array(roleResSchema);
  },
});

export type UserResSchema = z.infer<typeof userResSchema>;
