/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemDepartmentGetQueryResponse } from '../../models/AdminSystemDepartmentGet';

import { createAdminSystemDepartmentGetQueryResponseFaker } from '../../mocks/departmentController/createAdminSystemDepartmentGetFaker';

export function adminSystemDepartmentGetHandler(
  data?: AdminSystemDepartmentGetQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response),
) {
  return http.get('/api/v1/admin_system/department/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemDepartmentGetQueryResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
