/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemDepartmentPutMutationResponse } from '../../models/AdminSystemDepartmentPut';

import { createAdminSystemDepartmentPutMutationResponseFaker } from '../../mocks/departmentController/createAdminSystemDepartmentPutFaker';

export function adminSystemDepartmentPutHandler(
  data?: AdminSystemDepartmentPutMutationResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Response),
) {
  return http.put('/api/v1/admin_system/department/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemDepartmentPutMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
