/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemDepartmentDeleteMutationResponse } from '../../models/AdminSystemDepartmentDelete';

import { createAdminSystemDepartmentDeleteMutationResponseFaker } from '../../mocks/departmentController/createAdminSystemDepartmentDeleteFaker';

export function adminSystemDepartmentDeleteHandler(
  data?: AdminSystemDepartmentDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response),
) {
  return http.delete('/api/v1/admin_system/department/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemDepartmentDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
