/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemDepartmentsDeleteMutationResponse } from '../../models/AdminSystemDepartmentsDelete';

import { createAdminSystemDepartmentsDeleteMutationResponseFaker } from '../../mocks/departmentController/createAdminSystemDepartmentsDeleteFaker';

export function adminSystemDepartmentsDeleteHandler(
  data?: AdminSystemDepartmentsDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
  return http.post('/api/v1/admin_system/department/delete', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemDepartmentsDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
