/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemDepartmentPostMutationResponse } from '../../models/AdminSystemDepartmentPost';

import { createAdminSystemDepartmentPostMutationResponseFaker } from '../../mocks/departmentController/createAdminSystemDepartmentPostFaker';

export function adminSystemDepartmentPostHandler(
  data?: AdminSystemDepartmentPostMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
  return http.post('/api/v1/admin_system/department', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemDepartmentPostMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
