/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { departmentResSchema } from '../departmentResSchema';

export const adminSystemDepartmentGetPathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemDepartmentGetPathParamsSchema = z.infer<typeof adminSystemDepartmentGetPathParamsSchema>;

/**
 * @description success
 */
export const adminSystemDepartmentGet200Schema = commonResSchema.and(
  z.object({
    get data() {
      return departmentResSchema;
    },
  }),
);

export type AdminSystemDepartmentGet200Schema = z.infer<typeof adminSystemDepartmentGet200Schema>;

export const adminSystemDepartmentGetQueryResponseSchema = adminSystemDepartmentGet200Schema;

export type AdminSystemDepartmentGetQueryResponseSchema = z.infer<typeof adminSystemDepartmentGetQueryResponseSchema>;
