/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { idsReqSchema } from '../idsReqSchema';

/**
 * @description 非查询返回
 */
export const adminSystemDepartmentsDelete200Schema = commonResSchema.and(
  z.object({
    data: z.string(),
  }),
);

export type AdminSystemDepartmentsDelete200Schema = z.infer<typeof adminSystemDepartmentsDelete200Schema>;

export const adminSystemDepartmentsDeleteMutationRequestSchema = idsReqSchema;

export type AdminSystemDepartmentsDeleteMutationRequestSchema = z.infer<typeof adminSystemDepartmentsDeleteMutationRequestSchema>;

export const adminSystemDepartmentsDeleteMutationResponseSchema = adminSystemDepartmentsDelete200Schema;

export type AdminSystemDepartmentsDeleteMutationResponseSchema = z.infer<typeof adminSystemDepartmentsDeleteMutationResponseSchema>;
