/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { emptyResSchema } from '../emptyResSchema';

export const adminSystemDepartmentDeletePathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemDepartmentDeletePathParamsSchema = z.infer<typeof adminSystemDepartmentDeletePathParamsSchema>;

/**
 * @description 非查询返回
 */
export const adminSystemDepartmentDelete200Schema = commonResSchema.and(
  z.object({
    data: z.string(),
  }),
);

export type AdminSystemDepartmentDelete200Schema = z.infer<typeof adminSystemDepartmentDelete200Schema>;

export const adminSystemDepartmentDeleteMutationRequestSchema = emptyResSchema;

export type AdminSystemDepartmentDeleteMutationRequestSchema = z.infer<typeof adminSystemDepartmentDeleteMutationRequestSchema>;

export const adminSystemDepartmentDeleteMutationResponseSchema = adminSystemDepartmentDelete200Schema;

export type AdminSystemDepartmentDeleteMutationResponseSchema = z.infer<typeof adminSystemDepartmentDeleteMutationResponseSchema>;
