/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonPageResSchema } from '../commonPageResSchema';
import { commonResSchema } from '../commonResSchema';
import { departmentResSchema } from '../departmentResSchema';

export const adminSystemDepartmentsQueryQueryParamsSchema = z
  .object({
    page_no: z.coerce.number().int().min(0).optional(),
    page_size: z.coerce.number().int().min(0).optional(),
  })
  .optional();

export type AdminSystemDepartmentsQueryQueryParamsSchema = z.infer<typeof adminSystemDepartmentsQueryQueryParamsSchema>;

/**
 * @description success
 */
export const adminSystemDepartmentsQuery200Schema = commonResSchema.and(
  z.object({
    get result() {
      return commonPageResSchema.and(
        z.object({
          get list() {
            return z.array(departmentResSchema);
          },
        }),
      );
    },
  }),
);

export type AdminSystemDepartmentsQuery200Schema = z.infer<typeof adminSystemDepartmentsQuery200Schema>;

export const adminSystemDepartmentsQueryQueryResponseSchema = adminSystemDepartmentsQuery200Schema;

export type AdminSystemDepartmentsQueryQueryResponseSchema = z.infer<typeof adminSystemDepartmentsQueryQueryResponseSchema>;
