/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { IdsReq } from '../models/IdsReq';

export function createIdsReqFaker(data?: Partial<IdsReq>): IdsReq {
  faker.seed([2021]);
  return {
    ...{ ids: faker.helpers.multiple(() => faker.string.alpha({ length: { min: 20, max: 20 } }), { count: 1 }) },
    ...(data || {}),
  };
}
