/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { MenuRes } from '../models/MenuRes';

import { createResourceFaker } from './createResourceFaker';

export function createMenuResFaker(data?: Partial<MenuRes>): MenuRes {
  faker.seed([2021]);
  return {
    ...{
      id: faker.string.numeric(20),
      created_at: faker.number.int(),
      updated_at: faker.number.int(),
      sort: faker.number.int(),
      status: faker.number.int(),
      title: faker.string.alpha(),
      icon: faker.string.alpha(),
      code: '000000',
      code_path: faker.string.alpha(),
      parent_id: faker.string.alpha(),
      menu_type: faker.string.alpha(),
      menu_path: faker.string.alpha(),
      level: faker.number.int(),
      properties: faker.string.alpha(),
      resources: faker.helpers.multiple(() => createResourceFaker()),
      children: [],
    },
    ...(data || {}),
  };
}
