/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { CommonSuccess } from '../models/CommonSuccess';

import { createCommonResFaker } from './createCommonResFaker';

export function createCommonSuccessFaker(data?: Partial<CommonSuccess>): CommonSuccess {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: faker.string.alpha() });
}
