/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { DepartmentRes } from '../models/DepartmentRes';

export function createDepartmentResFaker(data?: Partial<DepartmentRes>): DepartmentRes {
  faker.seed([2021]);
  return {
    ...{
      id: faker.string.numeric(20),
      created_at: faker.number.int(),
      updated_at: faker.number.int(),
      sort: faker.number.int(),
      department_name: faker.string.alpha(),
      remark: faker.string.alpha(),
      parent_id: faker.string.alpha(),
      path: faker.string.alpha(),
      level: faker.number.int(),
      children: [],
    },
    ...(data || {}),
  };
}
