/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { RoleRes } from '../models/RoleRes';

export function createRoleResFaker(data?: Partial<RoleRes>): RoleRes {
  faker.seed([2021]);
  return {
    ...{
      id: faker.string.numeric(20),
      created_at: faker.number.int(),
      updated_at: faker.number.int(),
      sort: faker.number.int(),
      role_name: faker.string.alpha(),
      code: '000000',
      remark: faker.string.alpha(),
      menu_ids: faker.helpers.multiple(() => faker.string.alpha()),
    },
    ...(data || {}),
  };
}
