/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { CommonPageRes } from '../models/CommonPageRes';

export function createCommonPageResFaker(data?: Partial<CommonPageRes>): CommonPageRes {
  faker.seed([2021]);
  return {
    ...{ page_no: 1, page_size: 10, total: 12, more: true },
    ...(data || {}),
  };
}
