/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { Resource } from '../models/Resource';

export function createResourceFaker(data?: Partial<Resource>): Resource {
  faker.seed([2021]);
  return {
    ...{ method: faker.string.alpha({ length: 32 }), path: faker.string.alpha({ length: 512 }) },
    ...(data || {}),
  };
}
