/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AccountInfoRes } from '../models/AccountInfoRes';

export function createAccountInfoResFaker(data?: Partial<AccountInfoRes>): AccountInfoRes {
  faker.seed([2021]);
  return {
    ...{ email: faker.internet.email(), name: faker.string.alpha(), nickname: faker.string.alpha(), phone: '18688886666', avatar: faker.image.avatar() },
    ...(data || {}),
  };
}
