/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { EmptyRes } from '../models/EmptyRes';

export function createEmptyResFaker(data?: Partial<EmptyRes>): EmptyRes {
  faker.seed([2021]);
  return {
    ...{},
    ...(data || {}),
  };
}
