/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import { createCommonResFaker } from './createCommonResFaker';

export function createUnknownErrorFaker() {
  faker.seed([2021]);
  return createCommonResFaker();
}
