/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { CommonRes } from '../models/CommonRes';

export function createCommonResFaker(data?: Partial<CommonRes>): CommonRes {
  faker.seed([2021]);
  return {
    ...{ t: faker.date.recent().getTime().toString(), success: faker.datatype.boolean(1), code: '000000', msg: 'OK' },
    ...(data || {}),
  };
}
