/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { PositionRes } from '../models/PositionRes';

export function createPositionResFaker(data?: Partial<PositionRes>): PositionRes {
  faker.seed([2021]);
  return {
    ...{
      id: faker.string.numeric(20),
      created_at: faker.number.int(),
      updated_at: faker.number.int(),
      sort: faker.number.int(),
      position_name: faker.string.alpha(),
      code: '000000',
      remark: faker.string.alpha(),
    },
    ...(data || {}),
  };
}
