/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { MenusRes } from '../models/MenusRes';

export function createMenusResFaker(data?: Partial<MenusRes>): MenusRes {
  faker.seed([2021]);
  return {
    ...{ code_path: faker.string.alpha(), icon: faker.string.alpha(), menu_type: faker.string.alpha(), children: [] },
    ...(data || {}),
  };
}
