/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { JwtResponse } from '../models/JwtResponse';

export function createJwtResponseFaker(data?: Partial<JwtResponse>): JwtResponse {
  faker.seed([2021]);
  return {
    ...{
      access_token: faker.string.alpha(),
      access_expire: faker.number.float({ min: 0 }),
      refresh_token: faker.string.alpha(),
      refresh_expire: faker.number.float({ min: 0 }),
    },
    ...(data || {}),
  };
}
