/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { UserRes } from '../models/UserRes';

import { createDepartmentResFaker } from './createDepartmentResFaker';
import { createPositionResFaker } from './createPositionResFaker';
import { createRoleResFaker } from './createRoleResFaker';

export function createUserResFaker(data?: Partial<UserRes>): UserRes {
  faker.seed([2021]);
  return {
    ...{
      id: faker.string.numeric(20),
      created_at: faker.number.int(),
      updated_at: faker.number.int(),
      status: faker.number.int(),
      email: faker.internet.email(),
      name: faker.string.alpha(),
      nickname: faker.string.alpha(),
      phone: '18688886666',
      avatar: faker.image.avatar(),
      remark: faker.string.alpha(),
      department: createDepartmentResFaker(),
      positions: faker.helpers.multiple(() => createPositionResFaker()),
      roles: faker.helpers.multiple(() => createRoleResFaker()),
    },
    ...(data || {}),
  };
}
