/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemUsersQueryQueryParams, AdminSystemUsersQueryQueryResponse } from '../../models/AdminSystemUsersQuery';

import { adminSystemUsersQueryQueryResponseSchema } from '../../zod/userController/adminSystemUsersQuerySchema';

export function getAdminSystemUsersQueryUrl() {
  return `/api/v1/admin_system/user` as const;
}

/**
 * @summary 查询多个用户
 * {@link /api/v1/admin_system/user}
 */
export async function adminSystemUsersQuery(
  { params }: { params?: AdminSystemUsersQueryQueryParams },
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemUsersQueryQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemUsersQueryUrl().toString(),
    params,
    ...requestConfig,
  });
  return { ...res, data: adminSystemUsersQueryQueryResponseSchema.parse(res.data) };
}
