/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type { AdminSystemUserGetPathParams, AdminSystemUserGetQueryResponse } from '../../models/AdminSystemUserGet';

import { adminSystemUserGetQueryResponseSchema } from '../../zod/userController/adminSystemUserGetSchema';

export function getAdminSystemUserGetUrl({ id }: { id: AdminSystemUserGetPathParams['id'] }) {
  return `/api/v1/admin_system/user/${id}` as const;
}

/**
 * @summary 查询用户
 * {@link /api/v1/admin_system/user/:id}
 */
export async function adminSystemUserGet({ id }: { id: AdminSystemUserGetPathParams['id'] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemUserGetQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemUserGetUrl({ id }).toString(),
    ...requestConfig,
  });
  return { ...res, data: adminSystemUserGetQueryResponseSchema.parse(res.data) };
}
