/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemUsersDeleteMutationRequest, AdminSystemUsersDeleteMutationResponse } from '../../models/AdminSystemUsersDelete';

import {
  adminSystemUsersDeleteMutationRequestSchema,
  adminSystemUsersDeleteMutationResponseSchema,
} from '../../zod/userController/adminSystemUsersDeleteSchema';

export function getAdminSystemUsersDeleteUrl() {
  return `/api/v1/admin_system/user/delete` as const;
}

/**
 * @summary 删除多个用户
 * {@link /api/v1/admin_system/user/delete}
 */
export async function adminSystemUsersDelete(
  { data }: { data: AdminSystemUsersDeleteMutationRequest },
  config: Partial<RequestConfig<AdminSystemUsersDeleteMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemUsersDeleteMutationRequestSchema.parse(data);
  const res = await request<AdminSystemUsersDeleteMutationResponse, ResponseErrorConfig<Error>, AdminSystemUsersDeleteMutationRequest>({
    method: 'POST',
    url: getAdminSystemUsersDeleteUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemUsersDeleteMutationResponseSchema.parse(res.data) };
}
