/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemUserGetByEmailQueryParams, AdminSystemUserGetByEmailQueryResponse } from '../../models/AdminSystemUserGetByEmail';

import { adminSystemUserGetByEmailQueryResponseSchema } from '../../zod/userController/adminSystemUserGetByEmailSchema';

export function getAdminSystemUserGetByEmailUrl() {
  return `/api/v1/admin_system/user/byemail` as const;
}

/**
 * @summary 查询用户通过email
 * {@link /api/v1/admin_system/user/byemail}
 */
export async function adminSystemUserGetByEmail(
  { params }: { params: AdminSystemUserGetByEmailQueryParams },
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemUserGetByEmailQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemUserGetByEmailUrl().toString(),
    params,
    ...requestConfig,
  });
  return { ...res, data: adminSystemUserGetByEmailQueryResponseSchema.parse(res.data) };
}
