/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemUserPostMutationRequest, AdminSystemUserPostMutationResponse } from '../../models/AdminSystemUserPost';

import { adminSystemUserPostMutationRequestSchema, adminSystemUserPostMutationResponseSchema } from '../../zod/userController/adminSystemUserPostSchema';

export function getAdminSystemUserPostUrl() {
  return `/api/v1/admin_system/user` as const;
}

/**
 * @summary 新增用户
 * {@link /api/v1/admin_system/user}
 */
export async function adminSystemUserPost(
  { data }: { data: AdminSystemUserPostMutationRequest },
  config: Partial<RequestConfig<AdminSystemUserPostMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemUserPostMutationRequestSchema.parse(data);
  const res = await request<AdminSystemUserPostMutationResponse, ResponseErrorConfig<Error>, AdminSystemUserPostMutationRequest>({
    method: 'POST',
    url: getAdminSystemUserPostUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemUserPostMutationResponseSchema.parse(res.data) };
}
