/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemUserPutMutationRequest, AdminSystemUserPutMutationResponse, AdminSystemUserPutPathParams } from '../../models/AdminSystemUserPut';

import { adminSystemUserPutMutationRequestSchema, adminSystemUserPutMutationResponseSchema } from '../../zod/userController/adminSystemUserPutSchema';

export function getAdminSystemUserPutUrl({ id }: { id: AdminSystemUserPutPathParams['id'] }) {
  return `/api/v1/admin_system/user/${id}` as const;
}

/**
 * @summary 修改用户
 * {@link /api/v1/admin_system/user/:id}
 */
export async function adminSystemUserPut(
  { id, data }: { id: AdminSystemUserPutPathParams['id']; data?: AdminSystemUserPutMutationRequest },
  config: Partial<RequestConfig<AdminSystemUserPutMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemUserPutMutationRequestSchema.parse(data);
  const res = await request<AdminSystemUserPutMutationResponse, ResponseErrorConfig<Error>, AdminSystemUserPutMutationRequest>({
    method: 'PUT',
    url: getAdminSystemUserPutUrl({ id }).toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemUserPutMutationResponseSchema.parse(res.data) };
}
