/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { adminSystemUserDelete } from './adminSystemUserDelete';
import { adminSystemUserGet } from './adminSystemUserGet';
import { adminSystemUserGetByEmail } from './adminSystemUserGetByEmail';
import { adminSystemUserPost } from './adminSystemUserPost';
import { adminSystemUserPut } from './adminSystemUserPut';
import { adminSystemUsersDelete } from './adminSystemUsersDelete';
import { adminSystemUsersQuery } from './adminSystemUsersQuery';

export function userService() {
  return {
    adminSystemUserPost,
    adminSystemUsersQuery,
    adminSystemUsersDelete,
    adminSystemUserDelete,
    adminSystemUserPut,
    adminSystemUserGet,
    adminSystemUserGetByEmail,
  };
}
