/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AccountLogoutMutationResponse } from '../../models/AccountLogout';

import { createCommonResFaker } from '../createCommonResFaker';
import { createEmptyResFaker } from '../createEmptyResFaker';

/**
 * @description success
 */
export function createAccountLogout200Faker() {
  faker.seed([2021]);
  return createCommonResFaker();
}

export function createAccountLogoutMutationRequestFaker() {
  faker.seed([2021]);
  return createEmptyResFaker();
}

export function createAccountLogoutMutationResponseFaker(data?: Partial<AccountLogoutMutationResponse>): AccountLogoutMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAccountLogout200Faker()]);
}
