/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AccountRefresh200, AccountRefreshMutationRequest, AccountRefreshMutationResponse } from '../../models/AccountRefresh';

import { createCommonResFaker } from '../createCommonResFaker';
import { createJwtResponseFaker } from '../createJwtResponseFaker';

/**
 * @description success
 */
export function createAccountRefresh200Faker(data?: Partial<AccountRefresh200>): AccountRefresh200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: createJwtResponseFaker() });
}

export function createAccountRefreshMutationRequestFaker(data?: Partial<AccountRefreshMutationRequest>): AccountRefreshMutationRequest {
  faker.seed([2021]);
  return {
    ...{
      refresh_token:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXBhcnRtZW50SUQiOiIiLCJleHAiOjE3NTMwNjI0ODQsImlhdCI6MTc1Mjk3NjA4NCwicG9zaXRpb25JRCI6IiIsInJvbGVDb2RlIjoiU1VQRVIiLCJ1c2VySUQiOiJkMDI1YXQ5c2liZnM3M2FmODhhZyJ9.eBSWn93KQORz14qzZuhwqycLo-o7l9Z8tgdRMMPhOTM',
    },
    ...(data || {}),
  };
}

export function createAccountRefreshMutationResponseFaker(data?: Partial<AccountRefreshMutationResponse>): AccountRefreshMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAccountRefresh200Faker()]);
}
