/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AccountRefresh200, AccountRefreshMutationRequest, AccountRefreshMutationResponse } from '../../models/AccountRefresh';

import { createCommonResFaker } from '../createCommonResFaker';
import { createJwtResponseFaker } from '../createJwtResponseFaker';

/**
 * @description success
 */
export function createAccountRefresh200Faker(data?: Partial<AccountRefresh200>): AccountRefresh200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: createJwtResponseFaker() });
}

export function createAccountRefreshMutationRequestFaker(data?: Partial<AccountRefreshMutationRequest>): AccountRefreshMutationRequest {
  faker.seed([2021]);
  return {
    ...{ refresh_token: faker.string.alpha() },
    ...(data || {}),
  };
}

export function createAccountRefreshMutationResponseFaker(data?: Partial<AccountRefreshMutationResponse>): AccountRefreshMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAccountRefresh200Faker()]);
}
