/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AccountInfo200, AccountInfoQueryResponse } from '../../models/AccountInfo';

import { createAccountInfoResFaker } from '../createAccountInfoResFaker';
import { createCommonResFaker } from '../createCommonResFaker';

/**
 * @description success
 */
export function createAccountInfo200Faker(data?: Partial<AccountInfo200>): AccountInfo200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: createAccountInfoResFaker() });
}

export function createAccountInfoQueryResponseFaker(data?: Partial<AccountInfoQueryResponse>): AccountInfoQueryResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAccountInfo200Faker()]);
}
