/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { BaseInitMutationRequest, BaseInitMutationResponse } from '../../models/BaseInit';

import { baseInitMutationRequestSchema, baseInitMutationResponseSchema } from '../../zod/systemController/baseInitSchema';

export function getBaseInitUrl() {
  return `/api/v1/admin_system/base/init` as const;
}

/**
 * @description 主要是数据库和基本数据
 * @summary 初始化系统
 * {@link /api/v1/admin_system/base/init}
 */
export async function baseInit(
  { data }: { data?: BaseInitMutationRequest },
  config: Partial<RequestConfig<BaseInitMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = baseInitMutationRequestSchema.parse(data);
  const res = await request<BaseInitMutationResponse, ResponseErrorConfig<Error>, BaseInitMutationRequest>({
    method: 'POST',
    url: getBaseInitUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: baseInitMutationResponseSchema.parse(res.data) };
}
