import * as icons from 'lucide-react';
import * as fs from 'node:fs';
import * as path from 'node:path';

const iconNames = Object.keys(icons).filter((name) => {
  return /^[A-Z]/.test(name) && !name.endsWith('Icon');
});

fs.writeFileSync(
  path.resolve(__dirname, '../src/lib/constant/lucide.ts'),
  `/* eslint-disable style/quotes,style/comma-dangle */
/**
 * Generated by scripts/lucide-whitelist.ts
 * Do not edit manually.
 */

export const LucideIconNames = ${JSON.stringify(iconNames, null, 2)};
export const LucideIconSet = new Set<string>([...LucideIconNames]);
`,
);
