/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type {
  AdminSystemPositionDeleteMutationRequest,
  AdminSystemPositionDeleteMutationResponse,
  AdminSystemPositionDeletePathParams,
} from '../../models/AdminSystemPositionDelete';

import {
  adminSystemPositionDeleteMutationRequestSchema,
  adminSystemPositionDeleteMutationResponseSchema,
} from '../../zod/positionController/adminSystemPositionDeleteSchema';

export function getAdminSystemPositionDeleteUrl({ id }: { id: AdminSystemPositionDeletePathParams['id'] }) {
  return `/api/v1/admin_system/position/${id}` as const;
}

/**
 * @summary 删除单个职位
 * {@link /api/v1/admin_system/position/:id}
 */
export async function adminSystemPositionDelete(
  { id, data }: { id: AdminSystemPositionDeletePathParams['id']; data?: AdminSystemPositionDeleteMutationRequest },
  config: Partial<RequestConfig<AdminSystemPositionDeleteMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemPositionDeleteMutationRequestSchema.parse(data);
  const res = await request<AdminSystemPositionDeleteMutationResponse, ResponseErrorConfig<Error>, AdminSystemPositionDeleteMutationRequest>({
    method: 'DELETE',
    url: getAdminSystemPositionDeleteUrl({ id }).toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemPositionDeleteMutationResponseSchema.parse(res.data) };
}
