/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemPositionGetPathParams, AdminSystemPositionGetQueryResponse } from '../../models/AdminSystemPositionGet';

import { adminSystemPositionGetQueryResponseSchema } from '../../zod/positionController/adminSystemPositionGetSchema';

export function getAdminSystemPositionGetUrl({ id }: { id: AdminSystemPositionGetPathParams['id'] }) {
  return `/api/v1/admin_system/position/${id}` as const;
}

/**
 * @summary 查询职位
 * {@link /api/v1/admin_system/position/:id}
 */
export async function adminSystemPositionGet(
  { id }: { id: AdminSystemPositionGetPathParams['id'] },
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemPositionGetQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemPositionGetUrl({ id }).toString(),
    ...requestConfig,
  });
  return { ...res, data: adminSystemPositionGetQueryResponseSchema.parse(res.data) };
}
