/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type { AdminSystemPositionPostMutationRequest, AdminSystemPositionPostMutationResponse } from '../../models/AdminSystemPositionPost';

import {
  adminSystemPositionPostMutationRequestSchema,
  adminSystemPositionPostMutationResponseSchema,
} from '../../zod/positionController/adminSystemPositionPostSchema';

export function getAdminSystemPositionPostUrl() {
  return `/api/v1/admin_system/position` as const;
}

/**
 * @summary 新增职位
 * {@link /api/v1/admin_system/position}
 */
export async function adminSystemPositionPost(
  { data }: { data: AdminSystemPositionPostMutationRequest },
  config: Partial<RequestConfig<AdminSystemPositionPostMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemPositionPostMutationRequestSchema.parse(data);
  const res = await request<AdminSystemPositionPostMutationResponse, ResponseErrorConfig<Error>, AdminSystemPositionPostMutationRequest>({
    method: 'POST',
    url: getAdminSystemPositionPostUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemPositionPostMutationResponseSchema.parse(res.data) };
}
