/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/request/restful/client';

import fetch from '@/request/restful/client';

import type { AdminSystemPositionsDeleteMutationRequest, AdminSystemPositionsDeleteMutationResponse } from '../../models/AdminSystemPositionsDelete';

import {
  adminSystemPositionsDeleteMutationRequestSchema,
  adminSystemPositionsDeleteMutationResponseSchema,
} from '../../zod/positionController/adminSystemPositionsDeleteSchema';

export function getAdminSystemPositionsDeleteUrl() {
  return `/api/v1/admin_system/position/delete` as const;
}

/**
 * @summary 删除多个职位
 * {@link /api/v1/admin_system/position/delete}
 */
export async function adminSystemPositionsDelete(
  { data }: { data: AdminSystemPositionsDeleteMutationRequest },
  config: Partial<RequestConfig<AdminSystemPositionsDeleteMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = adminSystemPositionsDeleteMutationRequestSchema.parse(data);
  const res = await request<AdminSystemPositionsDeleteMutationResponse, ResponseErrorConfig<Error>, AdminSystemPositionsDeleteMutationRequest>({
    method: 'POST',
    url: getAdminSystemPositionsDeleteUrl().toString(),
    data: requestData,
    ...requestConfig,
  });
  return { ...res, data: adminSystemPositionsDeleteMutationResponseSchema.parse(res.data) };
}
