/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RequestConfig, ResponseErrorConfig } from '@/lib/request/restful/client';

import fetch from '@/lib/request/restful/client';

import type { AdminSystemPositionsQueryQueryParams, AdminSystemPositionsQueryQueryResponse } from '../../models/AdminSystemPositionsQuery';

import { adminSystemPositionsQueryQueryResponseSchema } from '../../zod/positionController/adminSystemPositionsQuerySchema';

export function getAdminSystemPositionsQueryUrl() {
  return `/api/v1/admin_system/position` as const;
}

/**
 * @summary 查询多个职位
 * {@link /api/v1/admin_system/position}
 */
export async function adminSystemPositionsQuery(
  { params }: { params?: AdminSystemPositionsQueryQueryParams },
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<AdminSystemPositionsQueryQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAdminSystemPositionsQueryUrl().toString(),
    params,
    ...requestConfig,
  });
  return { ...res, data: adminSystemPositionsQueryQueryResponseSchema.parse(res.data) };
}
