/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { adminSystemPositionDelete } from './adminSystemPositionDelete';
import { adminSystemPositionGet } from './adminSystemPositionGet';
import { adminSystemPositionPost } from './adminSystemPositionPost';
import { adminSystemPositionPut } from './adminSystemPositionPut';
import { adminSystemPositionsDelete } from './adminSystemPositionsDelete';
import { adminSystemPositionsQuery } from './adminSystemPositionsQuery';

export function positionService() {
  return {
    adminSystemPositionPost,
    adminSystemPositionsQuery,
    adminSystemPositionsDelete,
    adminSystemPositionDelete,
    adminSystemPositionPut,
    adminSystemPositionGet,
  };
}
