/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemUserPostMutationResponse } from '../../models/AdminSystemUserPost';

import { createAdminSystemUserPostMutationResponseFaker } from '../../mocks/userController/createAdminSystemUserPostFaker';

export function adminSystemUserPostHandler(data?: AdminSystemUserPostMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response)) {
  return http.post('/api/v1/admin_system/user', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemUserPostMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
