/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemUsersDeleteMutationResponse } from '../../models/AdminSystemUsersDelete';

import { createAdminSystemUsersDeleteMutationResponseFaker } from '../../mocks/userController/createAdminSystemUsersDeleteFaker';

export function adminSystemUsersDeleteHandler(
  data?: AdminSystemUsersDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
  return http.post('/api/v1/admin_system/user/delete', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemUsersDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
