/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemUserDeleteMutationResponse } from '../../models/AdminSystemUserDelete';

import { createAdminSystemUserDeleteMutationResponseFaker } from '../../mocks/userController/createAdminSystemUserDeleteFaker';

export function adminSystemUserDeleteHandler(
  data?: AdminSystemUserDeleteMutationResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response),
) {
  return http.delete('/api/v1/admin_system/user/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemUserDeleteMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
