/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemUserGetByEmailQueryResponse } from '../../models/AdminSystemUserGetByEmail';

import { createAdminSystemUserGetByEmailQueryResponseFaker } from '../../mocks/userController/createAdminSystemUserGetByEmailFaker';

export function adminSystemUserGetByEmailHandler(
  data?: AdminSystemUserGetByEmailQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response),
) {
  return http.get('/api/v1/admin_system/user/byemail', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemUserGetByEmailQueryResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
