/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemUsersQueryQueryResponse } from '../../models/AdminSystemUsersQuery';

import { createAdminSystemUsersQueryQueryResponseFaker } from '../../mocks/userController/createAdminSystemUsersQueryFaker';

export function adminSystemUsersQueryHandler(data?: AdminSystemUsersQueryQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response)) {
  return http.get('/api/v1/admin_system/user', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemUsersQueryQueryResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
