/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemUserGetQueryResponse } from '../../models/AdminSystemUserGet';

import { createAdminSystemUserGetQueryResponseFaker } from '../../mocks/userController/createAdminSystemUserGetFaker';

export function adminSystemUserGetHandler(data?: AdminSystemUserGetQueryResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response)) {
  return http.get('/api/v1/admin_system/user/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemUserGetQueryResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
