/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AdminSystemUserPutMutationResponse } from '../../models/AdminSystemUserPut';

import { createAdminSystemUserPutMutationResponseFaker } from '../../mocks/userController/createAdminSystemUserPutFaker';

export function adminSystemUserPutHandler(data?: AdminSystemUserPutMutationResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Response)) {
  return http.put('/api/v1/admin_system/user/:id', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAdminSystemUserPutMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
