/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AccountLoginPasswordMutationResponse } from '../../models/AccountLoginPassword';

import { createAccountLoginPasswordMutationResponseFaker } from '../../mocks/accountController/createAccountLoginPasswordFaker';

export function accountLoginPasswordHandler(
  data?: AccountLoginPasswordMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response),
) {
  return http.post('/api/v1/admin_system/account/login_password', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAccountLoginPasswordMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
