/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw';

import type { AccountRefreshMutationResponse } from '../../models/AccountRefresh';

import { createAccountRefreshMutationResponseFaker } from '../../mocks/accountController/createAccountRefreshFaker';

export function accountRefreshHandler(data?: AccountRefreshMutationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response)) {
  return http.post('/api/v1/admin_system/account/refresh', (info) => {
    if (typeof data === 'function')
      return data(info);

    return new Response(JSON.stringify(data || createAccountRefreshMutationResponseFaker(data)), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
}
