/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { emptyResSchema } from '../emptyResSchema';

/**
 * @description success
 */
export const baseInit200Schema = commonResSchema;

export type BaseInit200Schema = z.infer<typeof baseInit200Schema>;

export const baseInitMutationRequestSchema = emptyResSchema;

export type BaseInitMutationRequestSchema = z.infer<typeof baseInitMutationRequestSchema>;

export const baseInitMutationResponseSchema = baseInit200Schema;

export type BaseInitMutationResponseSchema = z.infer<typeof baseInitMutationResponseSchema>;
