/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemRolesDelete200, AdminSystemRolesDeleteMutationResponse } from '../../models/AdminSystemRolesDelete';

import { createCommonResFaker } from '../createCommonResFaker';
import { createIdsReqFaker } from '../createIdsReqFaker';

/**
 * @description 非查询返回
 */
export function createAdminSystemRolesDelete200Faker(data?: Partial<AdminSystemRolesDelete200>): AdminSystemRolesDelete200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: faker.string.alpha() });
}

export function createAdminSystemRolesDeleteMutationRequestFaker() {
  faker.seed([2021]);
  return createIdsReqFaker();
}

export function createAdminSystemRolesDeleteMutationResponseFaker(
  data?: Partial<AdminSystemRolesDeleteMutationResponse>,
): AdminSystemRolesDeleteMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemRolesDelete200Faker()]);
}
