/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemRolePost200, AdminSystemRolePostMutationRequest, AdminSystemRolePostMutationResponse } from '../../models/AdminSystemRolePost';

import { createCommonResFaker } from '../createCommonResFaker';

/**
 * @description 非查询返回
 */
export function createAdminSystemRolePost200Faker(data?: Partial<AdminSystemRolePost200>): AdminSystemRolePost200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { result: faker.string.alpha() });
}

export function createAdminSystemRolePostMutationRequestFaker(data?: Partial<AdminSystemRolePostMutationRequest>): AdminSystemRolePostMutationRequest {
  faker.seed([2021]);
  return {
    ...{
      sort: faker.number.int({ min: 0 }),
      role_name: faker.string.alpha({ length: 255 }),
      code: '000000',
      remark: faker.string.alpha({ length: 255 }),
      menu_ids: faker.helpers.multiple(() => faker.string.alpha()),
    },
    ...(data || {}),
  };
}

export function createAdminSystemRolePostMutationResponseFaker(data?: Partial<AdminSystemRolePostMutationResponse>): AdminSystemRolePostMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemRolePost200Faker()]);
}
