/* eslint-disable unused-imports/no-unused-vars */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker';

import type { AdminSystemRoleDelete200, AdminSystemRoleDeleteMutationResponse, AdminSystemRoleDeletePathParams } from '../../models/AdminSystemRoleDelete';

import { createCommonResFaker } from '../createCommonResFaker';
import { createEmptyResFaker } from '../createEmptyResFaker';

export function createAdminSystemRoleDeletePathParamsFaker(data?: Partial<AdminSystemRoleDeletePathParams>): AdminSystemRoleDeletePathParams {
  faker.seed([2021]);
  return {
    ...{ id: faker.string.numeric(20) },
    ...(data || {}),
  };
}

/**
 * @description 非查询返回
 */
export function createAdminSystemRoleDelete200Faker(data?: Partial<AdminSystemRoleDelete200>): AdminSystemRoleDelete200 {
  faker.seed([2021]);
  return Object.assign({}, createCommonResFaker(), { data: faker.string.alpha() });
}

export function createAdminSystemRoleDeleteMutationRequestFaker() {
  faker.seed([2021]);
  return createEmptyResFaker();
}

export function createAdminSystemRoleDeleteMutationResponseFaker(data?: Partial<AdminSystemRoleDeleteMutationResponse>): AdminSystemRoleDeleteMutationResponse {
  faker.seed([2021]);
  return data || faker.helpers.arrayElement<any>([createAdminSystemRoleDelete200Faker()]);
}
