/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { idsReqSchema } from '../idsReqSchema';

/**
 * @description 非查询返回
 */
export const adminSystemRolesDelete200Schema = commonResSchema.and(
  z.object({
    data: z.string(),
  }),
);

export type AdminSystemRolesDelete200Schema = z.infer<typeof adminSystemRolesDelete200Schema>;

export const adminSystemRolesDeleteMutationRequestSchema = idsReqSchema;

export type AdminSystemRolesDeleteMutationRequestSchema = z.infer<typeof adminSystemRolesDeleteMutationRequestSchema>;

export const adminSystemRolesDeleteMutationResponseSchema = adminSystemRolesDelete200Schema;

export type AdminSystemRolesDeleteMutationResponseSchema = z.infer<typeof adminSystemRolesDeleteMutationResponseSchema>;
