/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { emptyResSchema } from '../emptyResSchema';

export const adminSystemRoleDeletePathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemRoleDeletePathParamsSchema = z.infer<typeof adminSystemRoleDeletePathParamsSchema>;

/**
 * @description 非查询返回
 */
export const adminSystemRoleDelete200Schema = commonResSchema.and(
  z.object({
    result: z.string(),
  }),
);

export type AdminSystemRoleDelete200Schema = z.infer<typeof adminSystemRoleDelete200Schema>;

export const adminSystemRoleDeleteMutationRequestSchema = emptyResSchema;

export type AdminSystemRoleDeleteMutationRequestSchema = z.infer<typeof adminSystemRoleDeleteMutationRequestSchema>;

export const adminSystemRoleDeleteMutationResponseSchema = adminSystemRoleDelete200Schema;

export type AdminSystemRoleDeleteMutationResponseSchema = z.infer<typeof adminSystemRoleDeleteMutationResponseSchema>;
