/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonPageResSchema } from '../commonPageResSchema';
import { commonResSchema } from '../commonResSchema';
import { roleResSchema } from '../roleResSchema';

export const adminSystemRolesQueryQueryParamsSchema = z
  .object({
    page_no: z.coerce.number().int().min(0).optional(),
    page_size: z.coerce.number().int().min(0).optional(),
    created_at: z.array(z.coerce.number().int()).max(2).optional(),
    updated_at: z.array(z.coerce.number().int()).max(2).optional(),
    role_name: z.string().optional(),
    code: z.string().optional(),
  })
  .optional();

export type AdminSystemRolesQueryQueryParamsSchema = z.infer<typeof adminSystemRolesQueryQueryParamsSchema>;

/**
 * @description success
 */
export const adminSystemRolesQuery200Schema = commonResSchema.and(
  z.object({
    get data() {
      return commonPageResSchema.and(
        z.object({
          get list() {
            return z.array(roleResSchema);
          },
        }),
      );
    },
  }),
);

export type AdminSystemRolesQuery200Schema = z.infer<typeof adminSystemRolesQuery200Schema>;

export const adminSystemRolesQueryQueryResponseSchema = adminSystemRolesQuery200Schema;

export type AdminSystemRolesQueryQueryResponseSchema = z.infer<typeof adminSystemRolesQueryQueryResponseSchema>;
