/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { roleResSchema } from '../roleResSchema';

export const adminSystemRoleGetPathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemRoleGetPathParamsSchema = z.infer<typeof adminSystemRoleGetPathParamsSchema>;

/**
 * @description success
 */
export const adminSystemRoleGet200Schema = commonResSchema.and(
  z.object({
    get result() {
      return roleResSchema;
    },
  }),
);

export type AdminSystemRoleGet200Schema = z.infer<typeof adminSystemRoleGet200Schema>;

export const adminSystemRoleGetQueryResponseSchema = adminSystemRoleGet200Schema;

export type AdminSystemRoleGetQueryResponseSchema = z.infer<typeof adminSystemRoleGetQueryResponseSchema>;
