/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';

/**
 * @description 非查询返回
 */
export const adminSystemRolePost200Schema = commonResSchema.and(
  z.object({
    result: z.string(),
  }),
);

export type AdminSystemRolePost200Schema = z.infer<typeof adminSystemRolePost200Schema>;

export const adminSystemRolePostMutationRequestSchema = z.object({
  sort: z.int().min(0).optional(),
  role_name: z.string().max(255),
  code: z.string().max(255),
  remark: z.string().max(255).optional(),
  menu_ids: z.array(z.string()).optional(),
});

export type AdminSystemRolePostMutationRequestSchema = z.infer<typeof adminSystemRolePostMutationRequestSchema>;

export const adminSystemRolePostMutationResponseSchema = adminSystemRolePost200Schema;

export type AdminSystemRolePostMutationResponseSchema = z.infer<typeof adminSystemRolePostMutationResponseSchema>;
