/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { resourceSchema } from '../resourceSchema';

/**
 * @description 非查询返回
 */
export const adminSystemMenuPost200Schema = commonResSchema.and(
  z.object({
    result: z.string(),
  }),
);

export type AdminSystemMenuPost200Schema = z.infer<typeof adminSystemMenuPost200Schema>;

export const adminSystemMenuPostMutationRequestSchema = z.object({
  sort: z.int().min(0).optional(),
  title: z.string().max(255),
  icon: z.string().max(512).optional(),
  code: z.string().max(255),
  parent_id: z.string().min(20).max(20).optional(),
  menu_type: z.enum(['page', 'button']),
  menu_path: z.string().max(255).optional(),
  properties: z.string().max(2048).optional(),
  get resources() {
    return z.array(resourceSchema).optional();
  },
});

export type AdminSystemMenuPostMutationRequestSchema = z.infer<typeof adminSystemMenuPostMutationRequestSchema>;

export const adminSystemMenuPostMutationResponseSchema = adminSystemMenuPost200Schema;

export type AdminSystemMenuPostMutationResponseSchema = z.infer<typeof adminSystemMenuPostMutationResponseSchema>;
