/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { resourceSchema } from '../resourceSchema';

export const adminSystemMenuPutPathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemMenuPutPathParamsSchema = z.infer<typeof adminSystemMenuPutPathParamsSchema>;

/**
 * @description 非查询返回
 */
export const adminSystemMenuPut200Schema = commonResSchema.and(
  z.object({
    result: z.string(),
  }),
);

export type AdminSystemMenuPut200Schema = z.infer<typeof adminSystemMenuPut200Schema>;

export const adminSystemMenuPutMutationRequestSchema = z.object({
  sort: z.int().min(0).optional(),
  status: z
    .union([z.literal(1), z.literal(2)])
    .describe('状态: 1正常 2禁用')
    .optional(),
  title: z.string().max(255).optional(),
  icon: z.string().max(512).optional(),
  properties: z.string().max(2048).optional(),
  get resources() {
    return z.array(resourceSchema).optional();
  },
});

export type AdminSystemMenuPutMutationRequestSchema = z.infer<typeof adminSystemMenuPutMutationRequestSchema>;

export const adminSystemMenuPutMutationResponseSchema = adminSystemMenuPut200Schema;

export type AdminSystemMenuPutMutationResponseSchema = z.infer<typeof adminSystemMenuPutMutationResponseSchema>;
