/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { emptyResSchema } from '../emptyResSchema';

export const adminSystemMenuDeletePathParamsSchema = z.object({
  id: z.string().min(20).max(20),
});

export type AdminSystemMenuDeletePathParamsSchema = z.infer<typeof adminSystemMenuDeletePathParamsSchema>;

/**
 * @description 非查询返回
 */
export const adminSystemMenuDelete200Schema = commonResSchema.and(
  z.object({
    data: z.string(),
  }),
);

export type AdminSystemMenuDelete200Schema = z.infer<typeof adminSystemMenuDelete200Schema>;

export const adminSystemMenuDeleteMutationRequestSchema = emptyResSchema;

export type AdminSystemMenuDeleteMutationRequestSchema = z.infer<typeof adminSystemMenuDeleteMutationRequestSchema>;

export const adminSystemMenuDeleteMutationResponseSchema = adminSystemMenuDelete200Schema;

export type AdminSystemMenuDeleteMutationResponseSchema = z.infer<typeof adminSystemMenuDeleteMutationResponseSchema>;
