/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { idsReqSchema } from '../idsReqSchema';

/**
 * @description 非查询返回
 */
export const adminSystemMenusDelete200Schema = commonResSchema.and(
  z.object({
    result: z.string(),
  }),
);

export type AdminSystemMenusDelete200Schema = z.infer<typeof adminSystemMenusDelete200Schema>;

export const adminSystemMenusDeleteMutationRequestSchema = idsReqSchema;

export type AdminSystemMenusDeleteMutationRequestSchema = z.infer<typeof adminSystemMenusDeleteMutationRequestSchema>;

export const adminSystemMenusDeleteMutationResponseSchema = adminSystemMenusDelete200Schema;

export type AdminSystemMenusDeleteMutationResponseSchema = z.infer<typeof adminSystemMenusDeleteMutationResponseSchema>;
