/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

import { commonResSchema } from '../commonResSchema';
import { menuResSchema } from '../menuResSchema';

/**
 * @description success
 */
export const adminSystemMenusQuery200Schema = commonResSchema.and(
  z.object({
    result: z.object({
      get list() {
        return z.array(menuResSchema).optional();
      },
    }),
  }),
);

export type AdminSystemMenusQuery200Schema = z.infer<typeof adminSystemMenusQuery200Schema>;

export const adminSystemMenusQueryQueryResponseSchema = adminSystemMenusQuery200Schema;

export type AdminSystemMenusQueryQueryResponseSchema = z.infer<typeof adminSystemMenusQueryQueryResponseSchema>;
